package messaging.domintf.contact.user;

import java.io.Serializable;
import java.util.Date;
/**
 * @author jmcnabb
 *
 */
public interface IUserProfile extends Serializable
{
	Date getActivationDate();
	String getActivationTime();
	String getActivatedByLastName();
	String getActivatedByFirstName();
	String getAgencyId();
	String getAgencyName();
	Date getTransferDate();
	Date getDeptTransferRequestDate();
	String getComments();
	Date getCreateDate();
	String getCreateTime();
	String getCreatedByFirstName();
	String getCreatedByLastName();
	String getCreatedByName();
	Date getDateOfBirth();
	String getInactivatedByLastName();
	String getInactivatedByFirstName();
	String getEmail();
	Date getInactivationDate();
	Date getInactivationRequestDate();
	String getInactivationTimeId();
	String getInactivationRequestTimeId();
	String getFirstName();
	String getGenericUserType();
	Date getLastLoginDate();
	String getLastName();
	String getMiddleName();
	String getPhoneNum();
	String getPublicInd();
	String getRequestorFirstName();
	String getRequestorLastName();
	String getRequestorName();
	String getSsn();
	String getTrainingInd();
	String getLogonId();
	String getUserStatus();
	String getPhoneExt();
	String getDepartmentId();
	String getDepartmentName();
	String getBadgeNum();
	String getOtherIdNum();
	String getOperatorId();
	String getOrgCode();
	String getUserType();
	String getUserTypeId();
	String getTitle();
	String getTransferTime();
	String getDeptTransferRequestTime();
	String getCreateOfficerProfileInd();
	void setActivationDate(Date activationDate);
	void setActivationTime(String activationTime);
	void setActivatedByLastName(String activatedByLastName);
	void setActivatedByFirstName(String activatedByFirstName);
	void setAgencyId(String agencyId);
	void setAgencyName(String agencyName);
	void setTransferDate(Date transferDate);
	void setDeptTransferRequestDate(Date transferRequestDate);
	void setTransferTime(String transferTime);
	void setDeptTransferRequestTime(String transferRequestTime);
	void setComments(String comments);
	void setCreateDate(Date createDate);
	void setCreateTime(String createTime);
	void setCreatedByFirstName(String createdByFirstName);
	void setCreatedByName(String createdByName);
	void setDateOfBirth(Date dateOfBirth);
	void setInactivatedByLastName(String inactivatedByLastName);
	void setInactivatedByFirstName(String inactivatedByFirstName);
	void setEmail(String email);
	void setInactivationDate(Date inactivationDate);
	void setInactivationTimeId(String inactivationTimeId);
	void setInactivationRequestDate(Date inactivationRequestDate);
	void setInactivationRequestTimeId(String inactivationRequestTimeId);
	void setFirstName(String firstName);
	void setBadgeNum(String badgeNum);
	void setOtherIdNum(String otherIdNum);
	void setLastLoginDate(Date lastLoginDate);
	void setLastName(String lastName);
	void setMiddleName(String middleName);
	void setPhoneNum(String phoneNum);
	void setPublicInd(String ind);
	void setRequestorFirstName(String requestorFirstName);
	void setRequestorLastName(String requestorLastName);
	void setRequestorName(String requestorName);
	void setSsn(String ssn);
	void setTrainingInd(String trainingInd);
	void setLogonId(String logonId);
	void setUserStatus(String userStatus);
	void setUserType(String userType);
	void setUserTypeId(String userTypeId);
	void setGenericUserType(String genericUserType);
	void setCreatedByLastName(String createdByLastName);
	void setPhoneExt(String phoneExt);
	void setDepartmentId(String departmentId);
	void setDepartmentName(String departmentName);
	void setOperatorId(String operatorId);
	void setOrgCode(String orgCode);
	void setTitle(String title);
	void setCreateOfficerProfileInd(String createOfficerProfileInd);
}
