/*
 * LogSignalForm.java
 *
 * Created on February 15, 2001, 7:10 AM
 */

package mojo.ui.logging;

import java.util.Iterator;
import java.util.Vector;

import mojo.km.config.MojoProperties;
import mojo.km.config.ServerProperties;
import mojo.km.logging.LogStream;
import javax.swing.JPanel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JCheckBox;

/**

 *
 * @author  eric
 * @version 
 * @modelguid {4AD65A9C-1FC7-4535-9C06-F54C2C5E66C5}
 */
public class LogSignalForm extends JPanel {

    /** Creates new form LogSignalForm 
     * @modelguid {D1E1E1B2-3FAC-4761-8970-C8188854423F}
     */
    public LogSignalForm() {
        initGUI ();
        buildServerList();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     * @modelguid {08F59038-3D18-457C-948A-0E22D1BE7F70}
     */
    private void initGUI() {//GEN-BEGIN:initComponents

        stackTraceCheck = new JCheckBox();
        stackTraceCheck.setText("Stack Trace");
        systemOutCheck = new JCheckBox();
        systemOutCheck.setText("System Out");
        systemOutCheck.setActionCommand("Standard Out");
        systemErrorCheck = new JCheckBox();
        systemErrorCheck.setText("System Error");
        serverList = new JList();
        serverList.setBorder(null);
        serverList.setSelectedIndex(0);
        serverList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        panel1 = new java.awt.Panel();
        applicationExceptionCheck = new JCheckBox();
        runtimeExceptionCheck = new JCheckBox();
        standardExceptionCheck = new JCheckBox();
        jPanel1 = new JPanel();
        sendButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        setLayout(new java.awt.BorderLayout());
        setMinimumSize(new java.awt.Dimension(200, 400));
        
        panel1.setLayout(new java.awt.GridLayout(7, 1));
        panel1.setFont(new java.awt.Font ("Dialog", 0, 11));
        panel1.setBackground(new java.awt.Color (204, 204, 204));
        panel1.setForeground(java.awt.Color.black);
        
        applicationExceptionCheck.setText("Application Exception");
          panel1.add(applicationExceptionCheck);
          
          
        runtimeExceptionCheck.setText("Runtime Exception");
          runtimeExceptionCheck.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  runtimeExceptionCheckActionPerformed(evt);
              }
          }
          );
          panel1.add(runtimeExceptionCheck);
          
          
        standardExceptionCheck.setText("Standard Exception");
          panel1.add(standardExceptionCheck);
          
          
          
          
          
          
          panel1.add(errorCheck);
          panel1.add(systemErrorCheck);
          panel1.add(systemOutCheck);
          panel1.add(stackTraceCheck);
          
          
          setBounds(new java.awt.Rectangle(0,0,415,255));
        add(panel1, java.awt.BorderLayout.CENTER);
        
        
        
        
        
        
        sendButton.setText("Send");
          sendButton.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  sendButtonActionPerformed(evt);
              }
          }
          );
          jPanel1.add(sendButton);
          
          
        closeButton.setText("Close");
          closeButton.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  closeButtonActionPerformed(evt);
              }
          }
          );
          jPanel1.add(closeButton);
          
          
        add(jPanel1, java.awt.BorderLayout.SOUTH);
        add(jPanel2, java.awt.BorderLayout.NORTH);
        add(jScrollPane1, java.awt.BorderLayout.WEST);
        
        jScrollPane1.getViewport().add(serverList);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(153, 153, 153), 1), "Servers", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)),
        javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 2, new java.awt.Color(0, 0, 0))));
        errorCheck.setText("Error Throwable");
    }//GEN-END:initComponents

	/** @modelguid {C3159F0D-21D3-4F8F-B267-0B9C29CC160D} */
  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
// Add your handling code here:
	System.exit(0);
  }//GEN-LAST:event_closeButtonActionPerformed

	/** @modelguid {B3B0009B-4A4E-4F34-A34B-14E2F5AC2B45} */
  private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
// Add your handling code here:
	short logFilter = 0;
    if (applicationExceptionCheck.isSelected())
    	logFilter =(short) (logFilter | LogStream.APPEXCEPTION);
    if (runtimeExceptionCheck.isSelected())
        logFilter = (short) (logFilter | LogStream.RUNTIMEEXCEPTION);
    if (standardExceptionCheck.isSelected())
        logFilter = (short) (logFilter | LogStream.EXCEPTION);
    if (systemOutCheck.isSelected())
        logFilter = (short) (logFilter | LogStream.OUTSTREAM);
    if (systemErrorCheck.isSelected())
        logFilter = (short) (logFilter | LogStream.ERRSTREAM);
    if (stackTraceCheck.isSelected())
        logFilter = (short) (logFilter | LogStream.STACKTRACE);
    if (errorCheck.isSelected())
        logFilter = (short) (logFilter | LogStream.ERROR);

    String serverName = (String) serverList.getSelectedValue();
    System.out.println("Level = " + logFilter + ", Server name = " + serverName );
    signalService.postLogLevel( logFilter, serverName );
  }//GEN-LAST:event_sendButtonActionPerformed

	/** @modelguid {2C8963FF-3CDA-4C1C-B4EF-B6B2DE5F704A} */
  private void runtimeExceptionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runtimeExceptionCheckActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_runtimeExceptionCheckActionPerformed

	/** @modelguid {25570F5B-4B61-4294-8C0C-28601F255DA8} */
  private void buildServerList()
  {
    Vector listData = new Vector();
    for (Iterator i = MojoProperties.getInstance().getServers(); i.hasNext(); ) {
    	ServerProperties lServer = (ServerProperties)i.next();
    	listData.add(lServer.getName());
	}
    listData.add( "All" );
    serverList.setListData(listData);
    serverList.setSelectedValue( "All", true );
    applicationExceptionCheck.setSelected( true );
    runtimeExceptionCheck.setSelected( true );
    standardExceptionCheck.setSelected( true );
    systemOutCheck.setSelected( true );
    systemErrorCheck.setSelected( true );
    stackTraceCheck.setSelected( true );
    errorCheck.setSelected( true );
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
	/** @modelguid {ACD54503-1E8F-413B-B890-3F152C0F9D24} */
  private java.awt.Panel panel1;
	/** @modelguid {3BDE2DDC-2D4B-4E81-9DF1-8F17AE8660B5} */
  private JCheckBox applicationExceptionCheck;
	/** @modelguid {C56C9F43-0417-4113-AD37-4C929A05C4E6} */
  private JCheckBox runtimeExceptionCheck;
	/** @modelguid {26163CA3-22B7-445E-AC1C-5AF876249C5F} */
  private JCheckBox standardExceptionCheck;
	/** @modelguid {67188D98-12C6-42C5-8A99-F38CA766D032} */
  private JCheckBox systemOutCheck;
	/** @modelguid {03E43701-FF74-479F-9942-D3CEE63E9C8D} */
  private JCheckBox systemErrorCheck;
	/** @modelguid {6444C3A7-723F-4139-9FA3-85ED2069929E} */
  private JCheckBox stackTraceCheck;
	/** @modelguid {5879B131-F2CF-4D10-B128-6E382A0D4D07} */
  private JList serverList;
	/** @modelguid {5EB76D5D-9CEE-46B5-BA68-5B5655710451} */
  private JPanel jPanel1;
	/** @modelguid {35B80D33-4167-460A-B192-CD7BAE7343E3} */
  private javax.swing.JButton sendButton;
	/** @modelguid {18430758-979D-442A-BDBE-865D12AEC53B} */
  private javax.swing.JButton closeButton;
  // End of variables declaration//GEN-END:variables
	/** @modelguid {3B3B2EAC-9510-42F8-8530-52EC4B205E9F} */
  private mojo.km.service.Logging.LogSignalService signalService = new  mojo.km.service.Logging.LogSignalService();
	/** @modelguid {C0EFDFA4-EEFA-41F5-AA81-8AA3D59F765F} */
  private JPanel jPanel2 = new JPanel();
	/** @modelguid {F8D296AF-C5BC-4912-A19D-C660EBF4664F} */
  private JScrollPane jScrollPane1 = new JScrollPane();
	/** @modelguid {CE6BDB7E-673C-4987-B0AC-FCC22B35DC10} */
  private JCheckBox errorCheck = new JCheckBox();
}
