/*
 * LogSignalFrame.java
 *
 * Created on February 15, 2001, 9:44 AM
 */

package mojo.ui.logging;

/**
 *
 * @author  eric
 * @version 
 * @modelguid {CBC1DDB9-901D-4D49-8DCF-739BE877700A}
 */
public class LogSignalFrame extends javax.swing.JFrame {

    /** Creates new form LogSignalFrame 
     * @modelguid {3C4F557B-6100-4D9D-88F7-909655E9C903}
     */
    public LogSignalFrame() {
        initComponents ();
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     * @modelguid {982F0AB3-1DE9-4023-A45C-BEF89578F907}
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        logSignalForm1 = new LogSignalForm();
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        
        getContentPane().add(logSignalForm1, java.awt.BorderLayout.NORTH);
        
    }//GEN-END:initComponents

    /** Exit the Application 
     * @modelguid {595D4922-30AA-46F4-9568-16A495BE2595}
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    * @modelguid {D20518C1-EE53-49E8-BC7E-36C42F207F53}
    */
    public static void main (String args[]) {
        new LogSignalFrame ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
	/** @modelguid {0D38FC93-E9D7-4CDE-B7BF-B29CA0893C8A} */
    private LogSignalForm logSignalForm1;
    // End of variables declaration//GEN-END:variables

}
