/* Generated by Together */

package mojo.km.scheduling;
import java.util.*;

/**
*  HourlySchedule calculates the next run date based on the FIRST run date.
*  The way it works: creates a Calendar based on today's date, and then resets the
*  hours, minutes, seconds and milliseconds of the calendar
*  to the first run timed date hours, minutes, seconds and milliseconds.
*  THEN 1 Hour is added to the date.
*
* 	This insures that the next run time date will have the same hours, min, sec, mill sec. as the
*   first run time date.
*
*   THIS CODE ASSUME SAME TIMEZONE FOR ITS CALCULATIONS.
* */


public class HourlySchedule implements ISchedule{

    public Date getNextRunDate(Date firstNotificationDate) {

		Calendar firstNotificationCalendar = Calendar.getInstance();
		firstNotificationCalendar.setTime(firstNotificationDate);

		Calendar currentDateCalendar = Calendar.getInstance();

		currentDateCalendar.set(Calendar.HOUR,firstNotificationCalendar.get(Calendar.HOUR));
		currentDateCalendar.set(Calendar.MINUTE,firstNotificationCalendar.get(Calendar.MINUTE));
		currentDateCalendar.set(Calendar.SECOND,firstNotificationCalendar.get(Calendar.SECOND));
		currentDateCalendar.set(Calendar.MILLISECOND,firstNotificationCalendar.get(Calendar.MILLISECOND));

		currentDateCalendar.add(Calendar.HOUR, 1);

		return currentDateCalendar.getTime();

    }
    public boolean isRunDateStillValid( Date runDate ) {
        return true;
    }

}
