/* Generated by Together */

package mojo.km.scheduling;
import java.util.Date;
/**
*	ISchedule represents provides the Scheduler with the next run date, or notification date.
*   Eevery event that registers with the scheduler, must have its own object that implements this interface.
*
*   If the return of getNextRunDate is null, then the notification will stop.
* 
*/
public interface ISchedule {

    /**
     *	Determines the next run date (or notification date).
     *   CONTRACT: If the return value is null, the notification will be permenantly stopped.
     *
     */

    public Date getNextRunDate(Date firstNotificationDate);
    public boolean isRunDateStillValid( Date runDate ) ;
}
