/* Generated by Together */

package mojo.km.scheduling;
import java.util.Date;

/**
*	A generic class that represents a One time only schedule.
*/
public class OnceSchedule implements ISchedule{
    	/**
         * Return of null is a signal to the scheduler that the task only needs to run once.
         */

    public Date getNextRunDate(Date firstNotificationDate){
        return null;
    }
    public boolean isRunDateStillValid( Date runDate ) {
        return true;
    }
        
}
