/* Generated by Together */

package mojo.es.mail.mailrequests;

import java.util.Iterator;

/**
 * @stereotype control
 * @eventPackage mojo.messaging.mailrequestsevents
 * @serverName UIProcess
 * @modelguid {4CF6106D-44DD-411B-8021-B972285E175E}
 */
public class MailController {

    /**
    * @stereotype design
    * @modelguid {A0709702-67C5-4970-8280-DD29D8D2A65E}
    * @commandList mojo.es.mail.mailrequests.SendEmailCommand
    */
    public void sendEmail(String subject, String fromAddress, String message, Iterator toAddresses) {}
}
