/* Generated by Together */

package mojo.km.exceptionhandling;
import java.util.Locale;

/**
 * Defines interface to be executed if exception handler is executed. 
 * @modelguid {6B5F7AEE-44FC-4EC5-8BC0-DA77717DED4F}
 */
public interface ExceptionCallback {
    /**
     * Logic to be executed if exeception is handler is executed.
     * @param locale
     * @param t
     * @modelguid {5AEDE9BC-CC29-419B-BD3B-E60BE3CEE5E6}
     */
     public void execute(Locale locale, Throwable t);
}
