/* Generated by Together */

package mojo.km.context;
import mojo.km.messaging.IEvent;

/**
* Command to provide no behavior.
* @modelguid {5554E9DD-D911-4D85-82ED-E3AC918DB0B3}
*/
public class CommandAdapter implements ICommand {
	/** @modelguid {F2BB24AF-0AD3-4036-8D73-C750CAF3AECC} */
    public void execute(IEvent event) throws Exception {
    }

	/** @modelguid {DF8FB1AE-FE87-4247-B3BD-DEFAFB10521E} */
    public void onRegister(IEvent event) {
    }

	/** @modelguid {22343B82-E9E9-4B62-8449-B4DF5970F73F} */
    public void onUnregister(IEvent event) {
    }

	/** @modelguid {A0AE0B8E-D6B1-49B4-8785-DC018401CA0B} */
    public void update(Object updateObject) {
    }
}
