/* Generated by Together */

package mojo.km.context;

/** @modelguid {38339D34-B49F-4A8D-B596-F3409D7A061E} */
public interface IGenericContext {
	/** @modelguid {8DDB5367-F6DA-4149-B4BD-C6F639495C23} */
    public mojo.km.dispatch.IDispatch getTrueReply();
}
