/* Generated by Together */

package mojo.km.context;

/**
 * Use the interface on a context if dispatch can not be overriden by a service reference. 
 * @modelguid {1704502F-D7A2-416D-8D04-2A033E41B1BC}
 */
public interface INoDispatchServiceOverride {
}
