/* Generated by Together */

package mojo.km.context;

/**
 * Use interface when command is required to post reply message via pub sub.
 @author Eric A Amundson
 * @modelguid {67CF6A3A-8D3D-41A8-932C-154EA118F595}
 */
public interface IPubSub {
}
