/* Generated by Together */

package mojo.km.context;

/**
 * Use interface when command is required to post a return.
 * @author Eric Amundson
 * @modelguid {E74D0CAA-A32B-491F-B885-A6802739E94C}
 */
public interface IReply {
}
