/* Generated by Together */

package mojo.km.security.helper;

import mojo.km.security.AccessLevel;
import java.io.Serializable;

/** @modelguid {A91D10BB-26F5-48B1-A893-DFB776412C87} */
public class Permission implements Comparable, Serializable
{
	/** @modelguid {53E08E86-7DE5-4969-B13A-16D33FD5A6FB} */
	private String featureList = "";
	/** @modelguid {4F8B8095-6A54-4AF4-B74C-661C031ADF52} */
	private String serviceName = "";
	/** @modelguid {9B1D2D55-2EE3-42FC-95A6-94D446A54D67} */
	private int serviceNameAccessLevel = AccessLevel.NONE.getCompareWeight();
	/** @modelguid {CE35B242-EAFD-42DD-9504-EB827BDDBABD} */
	private String propertyName = "";
	/** @modelguid {8477D412-2ACC-446E-B72A-C386E1334D4C} */
	private int propertyNameAccessLevel = AccessLevel.NONE.getCompareWeight();

	/** @modelguid {282120B5-C460-41D6-9B08-E55233BDF5C3} */
	public String getFeatureList()
	{
		return this.featureList;
	}

	/** @modelguid {CACC94EB-3280-47CE-91B2-9B21179DF91E} */
	public void setFeatureList(String featureList)
	{
		this.featureList = featureList;
	}

	/** @modelguid {89DC205E-EAD6-4F07-93E4-F093C0CC79E4} */
	public String getServiceName()
	{
		return this.serviceName;
	}

	/** @modelguid {3A4AF9ED-B0C1-48D1-A5CC-64E316A7F36E} */
	public void setServiceName(String serviceName)
	{
		this.serviceName = serviceName;
	}

	/** @modelguid {9C65D166-5BBB-4644-9EAB-662D330C3B94} */
	public int getServiceNameAccessLevel()
	{
		return this.serviceNameAccessLevel;
	}

	/** @modelguid {83F477DF-4D24-4C63-B6DC-A325B28F8C63} */
	public void setServiceNameAccessLevel(int serviceNameAccessLevel)
	{
		this.serviceNameAccessLevel = serviceNameAccessLevel;
	}

	/** @modelguid {F1C1EBCC-0197-4880-979D-87FBFCB671F3} */
	public void setServiceNameAccessLevel(AccessLevel serviceNameAccessLevel)
	{
		this.serviceNameAccessLevel = serviceNameAccessLevel.getCompareWeight();
	}
	
	/** @modelguid {324981BD-D4BC-475E-922F-DB8BFEAB56FC} */
	public String getPropertyName()
	{
		return this.propertyName;
	}

	/** @modelguid {1BB8692E-D2C4-4576-97D3-446D59EB5CA7} */
	public void setPropertyName(String propertyName)
	{
		this.propertyName = propertyName;
	}

	/** @modelguid {9A0AFEAB-FFA0-41CE-A08E-3252579BEBA3} */
	public int getPropertyNameAccessLevel()
	{
		return this.propertyNameAccessLevel;
	}

	/** @modelguid {8E821F10-3144-4BD6-8A8D-FF7B984914E3} */
	public void setPropertyNameAccessLevel(int propertyNameAccessLevel)
	{
		this.propertyNameAccessLevel = propertyNameAccessLevel;
	}

	/** @modelguid {B8A195A2-E7C9-452C-8E93-CEE88145C4F7} */
	public void setPropertyNameAccessLevel(AccessLevel propertyNameAccessLevel)
	{
		this.propertyNameAccessLevel = propertyNameAccessLevel.getCompareWeight();
	}    

	/** @modelguid {BA794BE5-1F7E-4E7D-8402-D5B202831ED4} */
	public int compareTo(Object value) throws ClassCastException {
        if (value == null) {
            return -1;
        }

        if (value instanceof Permission) {
            Permission newPermission = (Permission)value;

			if (newPermission.serviceNameAccessLevel == this.serviceNameAccessLevel)
			{
				if (newPermission.propertyNameAccessLevel == this.propertyNameAccessLevel)
				{
					return 0;
				}
				else if (newPermission.propertyNameAccessLevel > this.propertyNameAccessLevel)
				{
					return 1;
				}

				return -1;
			}
			else if (newPermission.serviceNameAccessLevel > this.serviceNameAccessLevel)
			{
				return 1;
			}
			else 
			{
				return -1;
			}
        }

        throw new ClassCastException("Can only compare Permission objects");
    }

	/**
     * Return a string representation of this PermissionType.
     * @overrides toString in class java.lang.Object
     * @return Return a string representation of this PermissionType.
     * @modelguid {FE493604-4258-4337-B36C-D9EAE6D178E7}
     */
    public String toString() 
	{
		StringBuffer sb = new StringBuffer();

		sb.append(this.getFeatureList());
		sb.append("|");
		sb.append(this.getServiceName());
		sb.append("|");
		sb.append(this.getServiceNameAccessLevel());
		sb.append("|");
		sb.append(this.getPropertyName());
		sb.append("|");
		sb.append(this.getPropertyNameAccessLevel());

		return sb.toString();
	}
}
