/* Generated by Together */

package mojo.pd;

/**
 * @stereotype control 
 * @contextManagerName mojo.km.context.Default.DefaultContextManager
 * @requestDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @replyDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @asyncDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @queueDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @pubSubDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @debugMode false
 * @connectionPool false
 * @workflowEnabled false
 * @projectClass
 * @dbPassword
 * @TransactionGroups
 * @MaxServers
 * @DataSource
 * @LastAccessed 0
 * @BuildTUXEDOConfig
 * @DriverClass
 * @serverUserID
 * @xaDataSourceClassName
 * @LoginCallback
 * @serverPassword
 * @ClientPubSub mojo.km.dispatch.Multicast.MCPubSubStrategy
 * @serverURL
 * @MinServers
 * @dbURL
 * @httpURL
 * @Context mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @RequestReply mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @dbUserID
 * @projectPath
 * @licensePath
 * @modelguid {6ABD3759-8F0A-4CDE-90AD-9DA4B5EF3BA4}
 */
public class ComplexController {
	//////
}
