/* Generated by Together */

package mojo.km.persistence;

import mojo.km.messaging.ResponseEvent;

/**
 * Has the new OID generated by the OID service.
 * @author Eric A Amundson
 * @version 1.0 
 * @modelguid {CB8B2278-3131-4D8C-8772-41020CCADD70}
 */
public class NewOID extends ResponseEvent {
	/** @modelguid {170D7CB3-6B9E-4936-9320-566BB036AD9E} */
    public NewOID() {
    }

    
	/** @modelguid {710BA600-CF2F-4BCC-AB12-0FE445A98725} */
    public String getNewOID(){
            return newOID;
        }

    
	/** @modelguid {0D6EFB36-9046-4188-B6CD-1086D1DA45CE} */
    public void setNewOID(String newOID){
            this.newOID = newOID;
        }

	/** @modelguid {C7B4193A-75A9-4D09-96B5-6D51B529CA7A} */
    private String newOID;
}
