/* Generated by Together */

package mojo.km.persistence;

/**
 * Houses current OID for each class.
 * @author Eric A Amundson 
 * @modelguid {C0A3FD34-8832-4CDB-823E-D9C356946AF3}
 */
public class OIDForClass extends PersistentObject {
    
	/** @modelguid {4C224A1E-6C21-4353-AE92-7349F1FE0088} */
    public String getNewOID(){
            return newOID;
        }

    
	/** @modelguid {30FB14D9-3E62-404A-9173-09562DBFE3B0} */
    public void setNewOID(String newOID){
            this.newOID = newOID;
        }

	/** @modelguid {3B66CB40-4344-4BF7-B2C3-D3060378AB9C} */
    private String newOID = "0";
}
