/* Generated by Together */

package mojo.km.persistence;

import mojo.km.messaging.RequestEvent;
/**
 * A event to get a new OID for persistent objects from a OID service.
 * @author Eric A Amundson
 * @version 1.0 
 * @modelguid {841EE935-9138-4281-BF87-CA045862CB54}
 */
public class RequestOID extends RequestEvent {
	/** @modelguid {3CB76AC5-66A8-44A5-A05D-312868029B7F} */
    public RequestOID() {
        setServer("OIDServer");
        setTopic("GenOID");
    }

    
	/** @modelguid {B571162D-52E0-40FC-9785-788BD5AF51A1} */
    public String getClassName(){
            return className;
        }

    
	/** @modelguid {E316D768-2C50-4E33-A2F6-BFF7DB54C4EA} */
    public void setClassName(String className){
            this.className = className;
        }

	/** @modelguid {07601271-4455-464F-A363-55AF79109E08} */
    private String className;
}
