<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!-- 04/01/2008	 Aswin Widjaja  Create JSP -->
<%-- 06/05/2008	 Leslie Deen	#52283 Add Help File --%>
<%-- 08/22/2008  Debbie Williamson #52481 Add validation. --%>
<!-- 08/23/2010  D Williamson   #67068 Changed tinyMCECustomInitMSO.js to tinyMCECustomInitCasenote.js -->
<!-- 01/28/2011  C Shimek       Activity #68635 - Added missing code for spell check to fix Help ticket #121893 -->
<!-- 09/27/2011  RCapestani - Activity #71306 add code to display reschedule reason text box and validate reschedule reason text -->
<!-- 02/22/2012  RCapestani - Activity #71306 add alert when event is rescheduled and date is in the past  -->

<!--TAG LIBRARIES NEEDED FOR STRUTS -->
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/jims2-presentation.tld" prefix="jims" %>
<%@page import="naming.UIConstants"%>
<%@page import="naming.PDCodeTableConstants"%>
<!-- TAB LIBRARIES NEEDED FOR MOJO -->
<%@ taglib uri="/WEB-INF/msp.tld" prefix="msp" %>
<!--LOCALE USED FOR INTERNATIONALIZATION-NOT USED YET -->


<!--BEGIN HEADER TAG-->
<head>
<msp:nocache />
<%-- Checks to make sure if the user is logged in. --%>
<%--msp:login / --%>
<meta http-equiv="Content-Language" content="en-us">
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1" %>
<META http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<META name="GENERATOR" content="IBM WebSphere Studio">
<META http-equiv="Content-Style-Type" content="text/css">

<!-- STYLE SHEET LINK -->
<link rel="stylesheet" type="text/css" href="/<msp:webapp/>css/base.css" />
<html:base />
<title>Common Supervision - csCalendar/groupOfficeVisit/groupOfficeVisitCreateUpdate.jsp</title>

<%--html:javascript formName="groupOfficeVisitCreateUpdate"/--%>
		<script type="text/javascript" src="/<msp:webapp/>js/timeout.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/CalendarPopup.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/AnchorPosition.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/common_supervision_util.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/customStrutsBasedValidation.js"></script>
		<script type="text/javascript" type="text/javascript" src="/<msp:webapp/>js/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
		<script type="text/javascript" type="text/javascript" src="/<msp:webapp/>js/tinyMCECustomInitCasenote.js"></script>
		<script type="text/javascript">
		//this function confirms that the user wants to create an event in the past
		function checkBackDate(theForm){
		      var dt = document.getElementsByName('currentOfficeVisit.eventDateStr')[0].value;
		      var theEventDate = new Date(dt);
		      var theDate = new Date();
		      var theMonth = theDate.getMonth()+1;
			  var theDay = theDate.getDate();
			  var theYear = theDate.getYear();
				if (theMonth < 10){
						theMonth = "0"+theMonth;
					}
					if (theDay < 10){
						theDay = "0"+theDay;
					}
	
				 var dateStr = (theMonth + "/" + theDay + "/" + theYear);
				 var theCurrentDate = new Date(dateStr);
				if (theEventDate <  theCurrentDate){
					return confirm("Event Date is in the past.\nClick Ok if you want to continue.")
				}		     
		}
		  function validateDateField(theForm) {
		      clearAllValArrays();		    
		      customValRequired("currentOfficeVisit.eventDateStr", "<bean:message key='errors.required' arg0='Event Date'/>","");
		      addMMDDYYYYDateValidation("currentOfficeVisit.eventDateStr","Event Date must be in date format (mm/dd/yyyy). ");
		     
		      return validateCustomStrutsBasedJS(theForm);
     	  }

    <%-- Please leave Purpose and Narrative fields at 7000 even though arg1 is 3500.  It needs to be 7000 to accommodate the hidden characters generated by TinyMCE. DAW --%>        
		  function validateField(theForm){		  
		      clearAllValArrays();
		      addAlphaNumericnSpaceValidation("currentOfficeVisit.eventName", "<bean:message key='errors.alphanumeric' arg0='Event Name'/>","");
		      customValMaxLength("currentOfficeVisit.eventName","<bean:message key='errors.maxlength' arg0='Event Name' arg1='20'/>","20");
		      addDefinedTinyMCEFieldMask("currentOfficeVisit.purpose","Purpose Text cannot have % or _ entries","");
		      customValMinLength("currentOfficeVisit.purpose","<bean:message key='errors.minlength' arg0='Purpose' arg1='1'/>","1");
		      customValMaxLength("currentOfficeVisit.purpose","<bean:message key='errors.maxlength' arg0='Purpose' arg1='3500'/>","7000");
		      add12HrTimeValidation("currentOfficeVisit.startTime","Start Time is not in proper 12 hour format, ie 03:15","");
		      add12HrTimeValidation("currentOfficeVisit.endTime","End Time is not in proper 12 hour format, ie 03:15","");
		      customValRequired("currentOfficeVisit.rescheduleReason", "<bean:message key='errors.required' arg0='Reschedule Reason'/>","");
		      customValMaxLength("currentOfficeVisit.rescheduleReason","<bean:message key='errors.maxlength' arg0='Reschedule Reason' arg1='3500'/>","7000");
		      addDefinedTinyMCEFieldMask("currentOfficeVisit.rescheduleReason","Reschedule Reason cannot have % or _ entries","");		      
		  return validateCustomStrutsBasedJS(theForm);
		  }
		  
		  function validateResults(theForm) {
		      customValRequired("currentOfficeVisit.outcome", "<bean:message key='errors.required' arg0='Outcome'/>","");
		      customValRequired("currentOfficeVisit.narrative", "<bean:message key='errors.required' arg0='Narrative'/>","");
		      customValMaxLength("currentOfficeVisit.narrative","<bean:message key='errors.maxlength' arg0='Narrative' arg1='3500'/>","7000");
		      addDefinedTinyMCEFieldMask("currentOfficeVisit.narrative","Narrative Text cannot have % or _ entries","");
		      return validateCustomStrutsBasedJS(theForm);
		  }
		</script>
		
	</head>
	<body topmargin="0" leftmargin="0">
		<html:form action="/displayCSGVSummary" target="content">
			<div align="center">
				<table width="98%" border="0" cellpadding="0" cellspacing="0" >
					<tr>
						<td valign="top"><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
					</tr>
					<tr>
						<td valign="top">
							<table width="100%" border="0" cellpadding="0" cellspacing="0" >
								<tr>
									<td valign="top">
										<tiles:insert page="../../common/commonSupervisionTabs.jsp" flush="true">
											<tiles:put name="tab" value="caseloadTab"/>
										</tiles:insert>	
									</td>
								</tr>
								<tr>
									<td bgcolor="#6699FF"><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
								</tr>
							</table>
							<table width="100%" border="0" cellpadding="0" cellspacing="0" class="borderTableBlue">
							<tr>
								<td><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
							</tr>
							<tr>
								<td valign="top" align="center">
									<!-- BEGIN HEADING TABLE -->
									<table width="100%">
										<tr>
											<td align="center" class="header">
											<bean:message key="title.CSCD" /> - 
											<logic:equal name="csCalendarOVForm" property="activityFlow" value="create">
												Create
											<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|48">
											</logic:equal>
											<logic:equal name="csCalendarOVForm" property="activityFlow" value="update">
												Update
												<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|15">
											</logic:equal>
											<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
												Reschedule
												<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|17">
											</logic:equal>
										Group Office Visit
											</td>
										</tr>
										<tr>
											<td align="center" class="errorAlert"><html:errors></html:errors></td>
										</tr>
									</table>
									<!-- END HEADING TABLE -->
									<!-- BEGIN INSTRUCTION TABLE -->
									<table width="98%" border="0">
										<tr>
											<td>
												<ul>
													<li>Enter required fields. Click Next.</li>
												</ul>
											</td>
										</tr>
										<tr>
											<td class="required" colspan="2"><bean:message key="prompt.3.diamond"/><bean:message key="prompt.requiredFieldsInstruction"/></td>
										</tr>
									</table>
									<!-- END INSTRUCTION TABLE -->
									
									<tiles:insert page="superviseeListTile.jsp" flush="true">
										<tiles:put name="superviseeList" beanName="csCalendarOVForm" beanProperty="superviseeList" />
									</tiles:insert>
									<div class="spacer4px"></div>
									
									<!-- BEGIN DETAIL TABLE -->
									<table align="center" width='98%' cellpadding="2" cellspacing="0" class="borderTableBlue">
										<tr class="detailHead">
											<td>Group Office Visit Information</td>
										</tr>
										<tr>
											<td colspan="2">
												<table width="100%" cellpadding="2" cellspacing="1">
													<tr>
														<td class="formDeLabel" nowrap>
															<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
																<bean:message key="prompt.3.diamond"/>
															</logic:equal>
															Office Visit Date</td>
														<td class="formDe">
														
														<logic:notEqual name="csCalendarOVForm" property="activityFlow" value="reschedule">
															<bean:write name="csCalendarOVForm" property="currentOfficeVisit.eventDate" formatKey="date.format.mmddyyyy"/>
														</logic:notEqual>
														
														<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
															<%-- Calendar popup javascript --%> 
															<html:text property="currentOfficeVisit.eventDateStr" size="10" maxlength="10"/>
																<script type="text/javascript" id="js1">
																	var cal1 = new CalendarPopup();
																	cal1.showYearNavigation();
																</script>
															<A HREF="#" onClick="cal1.select(document.forms[0]['currentOfficeVisit.eventDateStr'],'anchor1','MM/dd/yyyy'); return false;"
																NAME="anchor1" ID="anchor1" border="0"><bean:message key="prompt.3.calendar" /></A>
															
															</script>
														</logic:equal>
														
														</td>								
														<td class="formDeLabel" nowrap><bean:message key="prompt.eventName"/></td>
														<td class="formDe">
															<html:text property="currentOfficeVisit.eventName" size="20" maxlength="20"/>
														</td>										
													</tr>
													<tr>
														<td class="formDeLabel" nowrap>Start Time</td>
														<td class="formDe">
															    <html:text name="csCalendarOVForm" size="6" maxlength="5" property="currentOfficeVisit.startTime"/>
																             <html:select name="csCalendarOVForm" property="currentOfficeVisit.AMPMId1">
																	           <html:option value="AM">AM</html:option>
																	           <html:option value="PM">PM</html:option>
																            </html:select> 	
														</td>
														<td class="formDeLabel" nowrap>End Time</td>
														<td class="formDe">
															     <html:text name="csCalendarOVForm" size="6" maxlength="5" property="currentOfficeVisit.endTime"/>
																             <html:select name="csCalendarOVForm" property="currentOfficeVisit.AMPMId2">
																	           <html:option value="AM">AM</html:option>
																	           <html:option value="PM">PM</html:option>
																             </html:select>
														</td>
													</tr>
													<tr>
														<td class="formDeLabel" colspan="4">Purpose of Group Office Visit</td>
													</tr>
													<style>
														.mceEditor{
														width: "100%";
														height: "150"
														}
													</style>
													<tr class="formDe">
														<td colspan="4" align="center">
															<html:textarea styleClass="mceEditor" style="width:100%" rows="12" property="currentOfficeVisit.purpose"  ondblclick="myReverseTinyMCEFix(this)"/>
															<bean:define id="userAgency" name="csCalendarOVForm" property="agencyId"/>
															<tiles:insert page="../../common/spellCheckButtonTile.jsp" flush="false">
																<tiles:put name="agencyCode"><%=userAgency%></tiles:put>
															</tiles:insert> 
														</td>
													</tr>
													
													<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
														<tr>
															<td class="formDeLabel" colspan="4"><bean:message key="prompt.3.diamond"/> <bean:message key="prompt.rescheduledReason"/> - <bean:message key="prompt.casenote"/></td>
														</tr>
														<style>
															.mceEditor{
															width: "100%";
															height: "150"
															}
														</style>
														<tr class="formDe">
															<td colspan="4" align="center">
																<html:textarea styleClass="mceEditor" style="width:100%" rows="12" property="currentOfficeVisit.rescheduleReason"/>
															</td>
														</tr>
													</logic:equal>
													
													<logic:equal name="csCalendarOVForm" property="currentOfficeVisit.status" value="C">
														<tr>
															<td class="formDeLabel"><bean:message key="prompt.3.diamond"/>Outcome</td>
															<td class="formDe" colspan="3">
																<html:select name="csCalendarOVForm" property="currentOfficeVisit.outcomeCd">
																	<option>Please Select</option>
																	<html:optionsCollection name="csCalendarOVForm" property="filteredOVOutcomeList" value="supervisionCode" label="description"/>
																</html:select>
																
															</td>
														</tr>
														
														<tr>
															<td class="formDeLabel" colspan="4"><bean:message key="prompt.3.diamond"/>Narrative</td>
														</tr>
														<style>
															.mceEditor{
															width: "100%";
															height: "150"
															}
														</style>
														<tr class="formDe">
															<td colspan="4" align="center">
																<html:textarea styleClass="mceEditor" style="width:100%" rows="12" property="currentOfficeVisit.narrative"/>
															</td>
														</tr>
													</logic:equal>
												</table>
											</td>
										</tr>
									</table>
									<!-- BEGIN DETAIL TABLE -->
									<!-- BEGIN BUTTON TABLE -->
									<table border="0" width="100%">
										<tr>
											<td align="center">
												<html:submit property="submitAction"><bean:message key="button.back" /></html:submit>
												<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
												    <html:submit property="submitAction" onclick="return (myTinyMCEFix() && validateDateField(this.form) && validateField(this.form) && checkBackDate(this.Form))"><bean:message key="button.next" /></html:submit>
												</logic:equal>
												<logic:notEqual name="csCalendarOVForm" property="currentOfficeVisit.status" value="C">
												    <logic:notEqual name="csCalendarOVForm" property="activityFlow" value="reschedule">
												        <html:submit property="submitAction" onclick="return (myTinyMCEFix() && validateField(this.form) && checkBackDate(this.Form))"><bean:message key="button.next" /></html:submit>
												    </logic:notEqual>
												</logic:notEqual>
												<logic:equal name="csCalendarOVForm" property="currentOfficeVisit.status" value="C">
												    <html:submit property="submitAction" onclick="return (myTinyMCEFix() && validateField(this.form) && validateResults(this.form) && checkBackDate(this.Form))"><bean:message key="button.next" /></html:submit>
												</logic:equal>
												<html:submit property="submitAction"><bean:message key="button.cancel" /></html:submit>
											</td>
										</tr>
									</table>
									<!-- END BUTTON TABLE -->
								</td>
							</tr>
						</table><br>
					</td>
				</tr>
			</table><br></td>
		</tr>
	</table>
</td>
</tr>
</table>
</div>
<br>
</html:form>
<div align="center"><script type="text/javascript">renderBackToTop()</script></div>
</body>
</html:html>
