<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!-- THIS JSP IS USED FOR FOR CREATE, UPDATE, RESCHEDULE, AND RESULTS SCREENS-->
<!-- 01/30/2008	 Aswin Widjaja - Create JSP -->
<!-- 08/22/2008  Debbie Williamson - #52481 Added validation -->
<!-- 08/23/2010  D Williamson - #67068 Changed tinyMCECustomInitMSO.js to tinyMCECustomInitCasenote.js -->

<!--TAG LIBRARIES NEEDED FOR STRUTS -->
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/jims2-presentation.tld" prefix="jims" %>
<%@page import="naming.UIConstants"%>
<%@page import="naming.PDCodeTableConstants"%>
<!-- TAB LIBRARIES NEEDED FOR MOJO -->
<%@ taglib uri="/WEB-INF/msp.tld" prefix="msp" %>
<!--LOCALE USED FOR INTERNATIONALIZATION-NOT USED YET -->


<!--BEGIN HEADER TAG-->
<head>
<msp:nocache />
<%-- Checks to make sure if the user is logged in. --%>
<%--msp:login / --%>
<meta http-equiv="Content-Language" content="en-us">
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1" %>
<META http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<META name="GENERATOR" content="IBM WebSphere Studio">
<META http-equiv="Content-Style-Type" content="text/css">

<!-- STYLE SHEET LINK -->
<link rel="stylesheet" type="text/css" href="/<msp:webapp/>css/base.css" />
<html:base />
<title><bean:message key="title.heading" /> - csCalendar - otherEvent - otherEventCreateUpdate.jsp</title>
<!--THESE TWO LINES FOR STRUTS & JAVASCRIPTS VALIDATIONS-->
		<html:javascript formName="otherEventCreateUpdate"/>
		<script type="text/javascript" src="/<msp:webapp/>js/CalendarPopup.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/AnchorPosition.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/common_supervision_util.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/app.js"></script>
		<script type="text/javascript" src="/<msp:webapp/>js/customStrutsBasedValidation.js"></script>
		<script language="javascript" type="text/javascript" src="/<msp:webapp/>js/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
		<script language="javascript" type="text/javascript" src="/<msp:webapp/>js/tinyMCECustomInitCasenote.js"></script>
<script type="text/javascript">

        function validateDateField(theForm) {
		      clearAllValArrays();		    
		      customValRequired("eventDateStr", "<bean:message key='errors.required' arg0='Event Date'/>","");
		      addMMDDYYYYDateValidation("eventDateStr","Event Date must be in date format (mm/dd/yyyy). ");
		      return validateCustomStrutsBasedJS(theForm);
     	  }
     	  
   <%-- Please leave Purpose and Narrative fields at 7000 even though arg1 is 3500.  It needs to be 7000 to accommodate the hidden characters generated by TinyMCE. DAW --%>
		function validateOtherEventCreateUpdate(theForm){		
		      clearAllValArrays();
		      addAlphaNumericnSpaceValidation("eventName", "<bean:message key='errors.alphanumeric' arg0='Event Name'/>","");
		      customValMaxLength("eventName","<bean:message key='errors.maxlength' arg0='Event Name' arg1='20'/>","20");
		      addAlphaNumericNoFirstSpacewSymbolsValidation("purpose", "<bean:message key='errors.alphanumericWSymbols2' arg0='Purpose'/>","");
		      customValMinLength("purpose","<bean:message key='errors.minlength' arg0='Purpose' arg1='1'/>","1");
		      customValMaxLength("purpose","<bean:message key='errors.maxlength' arg0='Purpose' arg1='3500'/>","3500"); 
		      add12HrTimeValidation("startTime","Start Time is not in proper 12 hour format, ie 03:15","");
		      add12HrTimeValidation("endTime","End Time is not in proper 12 hour format, ie 03:15","");
	          return validateCustomStrutsBasedJS(theForm);		 
		 }
		 
		 function validateResults(theForm) {
			clearAllValArrays();
			trimCasenote("narrative");
			
			customValRequired("outcomeCd", "<bean:message key='errors.required' arg0='Outcome'/>","");
			customValRequired("narrative", "<bean:message key='errors.required' arg0='Narrative'/>","");
			customValMaxLength("narrative","<bean:message key='errors.maxlength' arg0='Narrative' arg1='3500'/>","7000");
			addDefinedTinyMCEFieldMask("narrative","Narrative Text cannot have % or _ entries","");
			add12HrTimeValidation("startTime","Start Time is not in proper 12 hour format, ie 03:15","");
			add12HrTimeValidation("endTime","End Time is not in proper 12 hour format, ie 03:15",""); 
			if (validateCustomStrutsBasedJS(theForm) && validateForBROnly(theForm.narrative.value, 'Narrative is required')){
				return true;
			}else {
				return false;
			}
		  }		
 </script>
		
	</head>
	<body topmargin=0 leftmargin="0" onKeyDown="checkEnterKeyAndSubmit(event, true)">
		<html:form action="/displayCSOtherEventSummary" target="content" onsubmit="myTinyMCEFix()">
			<div align="center">
				<table width="98%" border="0" cellpadding="0" cellspacing="0" >
					<tr>
						<td valign=top><img src="/<msp:webapp/>images/spacer.gif" height=5></td>
					</tr>
					<tr>
						<td valign=top>
							<table width=100% border="0" cellpadding="0" cellspacing="0" >
								<tr>
									<td valign=top>
										<!--tabs start-->
										<tiles:insert page="../../common/commonSupervisionTabs.jsp" flush="true">
											<tiles:put name="tab" value="calendarTab"/>
										</tiles:insert>	
										<!--tabs end-->
									</td>
								</tr>
								<tr>
									<td bgcolor=#6699FF><img src="/<msp:webapp/>images/spacer.gif" height=5></td>
								</tr>
							</table>
							<table width=100% border="0" cellpadding="0" cellspacing="0" class="borderTableBlue">
								<tr>
									<td><img src="/<msp:webapp/>images/spacer.gif" height=5></td>
								</tr>
								
								<logic:notEmpty name="csCalendarOtherForm" property="superviseeId">								
								<%--<logic:equal name="csCalendarOtherForm" property="context" value="S"> 
								slin: if the event has a SPN associated render the supervisee header and tabs - this supercedes the calendar context
								--%>
									<tr>
										<td valign="top" align="center">
											<!-- BEGIN SUPERVISEE INFORMATION TABLE  -->
											<tiles:insert page="../../common/superviseeHeader.jsp" flush="true"></tiles:insert>	
											<!-- END SUPERVISEE INFORMATION TABLE  -->
										</td>
									</tr>	
									<!-- BEGIN GREEN TABS TABLE -->		
									<tr>
										<td valign="top" align="center"> 
											<table width="98%" border="0" cellpadding="0" cellspacing="0">
												<tr>
													<td><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
												</tr>						
												<tr>
													<td valign="top">
														<tiles:insert page="../../common/caseloadCSCDSubTabs.jsp" flush="true">
															<tiles:put name="tab" value="CalendarTab"/> 
														</tiles:insert>					
													</td>
												</tr>
												<tr>
													<td  bgcolor=#33cc66><img src="/<msp:webapp/>js/images/spacer.gif" height="5"></td> 
												</tr>
											</table>
										</td>
									</tr>		
									<!-- END GREEN TABS TABLE -->				
									<tr>
										<td valign="top" align="center">
											<!-- BEGIN GREEN BORDER TABLE -->					
											<table width="98%" border="0" cellpadding="0" cellspacing="0" class="borderTableGreen">
								<%--</logic:equal>	--%>	
								</logic:notEmpty>
									
								<tr>
									<td valign=top align=center>
										<!--header area start-->

										<!-- BEGIN HEADING TABLE -->
										<table width=100%>
											<tr>
												<td align="center" class="header">CSCD -
													<logic:equal name="csCalendarOtherForm" property="activityFlow" value="create">
														<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|33">
														Create</logic:equal>
													<logic:equal name="csCalendarOtherForm" property="activityFlow" value="update">
														<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|36">
														Update</logic:equal>
													<logic:equal name="csCalendarOtherForm" property="activityFlow" value="reschedule">
														<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|38">
														Reschedule</logic:equal>
														Other Event
													<logic:equal name="csCalendarOtherForm" property="activityFlow" value="enterResults">
														<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|41">
														Results</logic:equal>
												</td>
											</tr>
										</table>
										<!-- END HEADING TABLE -->										
										<!-- BEGIN INSTRUCTION TABLE -->
										<table width="98%" border="0">
											<tr>
												<td>
													<ul>
														<li>Enter required fields. Click Next.</li>
													</ul>
												</td>
											</tr>
											<tr>
												<td class="required" colspan="2"><bean:message key="prompt.3.diamond"/><bean:message key="prompt.requiredFieldsInstruction"/></td>
											</tr>
										</table>
										<!-- END INSTRUCTION TABLE -->
										<!-- BEGIN DETAIL TABLE -->
											<tiles:insert page="otherEventCreateUpdateTile.jsp" flush="true">
												<tiles:put name="csCalendarOtherForm" beanName="csCalendarOtherForm" />
											</tiles:insert>	
											<div class=spacer4px></div>											
										<!-- BEGIN BUTTON TABLE -->
										<table border="0" width="100%">
											<tr>
												<td align="center">
													<html:submit property="submitAction"><bean:message key="button.back" /></html:submit>
													<logic:notEqual name="csCalendarOtherForm" property="statusCd" value="C" > 
													  <jims:if name="csCalendarOtherForm" property="activityFlow" op="equal" value="create">
														<jims:or name="csCalendarOtherForm" property="activityFlow" op="equal" value="update" />														
														<jims:then>
													        <html:submit property="submitAction" onclick="return validateOtherEventCreateUpdate(this.form)"><bean:message key="button.next" /></html:submit>
													    </jims:then>
													  </jims:if>
													</logic:notEqual>        
													<jims:if name="csCalendarOtherForm" property="activityFlow" op="equal" value="enterResults">
														<jims:or name="csCalendarOtherForm" property="statusCd" op="equal" value="C" />
														<jims:then>
														    <html:submit property="submitAction" onclick="return( myTinyMCEFix()&& validateResults(this.form))"><bean:message key="button.next" /></html:submit>
														</jims:then>
													</jims:if>
													<jims:if name="csCalendarOtherForm" property="activityFlow" op="equal" value="reschedule">
													    <jims:then>
													        <html:submit property="submitAction" onclick="return( validateDateField(this.form)&& validateOtherEventCreateUpdate(this.form))"><bean:message key="button.next" /></html:submit>
													    </jims:then>
													</jims:if>    
													<html:submit property="submitAction"><bean:message key="button.cancel" /></html:submit>										
												</td>
											</tr>
										</table>
										<!-- END BUTTON TABLE -->
										<!-- END DETAIL TABLE -->
									</td>
								</tr>
								<logic:present name="csCalendarDisplayForm">
									<logic:equal name="csCalendarDisplayForm" property="context" value="S">
										</table><br></td></tr>
									</logic:equal>	
								</logic:present>
							</table><br>
						</td>
					</tr>
				</table><br>
				<!--casefile tabs end-->
			</td>
		</tr>
	</table>
	<!-- END  TABLE -->
</div>
<br>
</html:form>
<div align=center><script type="text/javascript">renderBackToTop()</script></div></body>
</html:html>
