/* Generated by Together */

package mojo.km.units;

/** @stereotype interface 
 * @modelguid {BA5C85C0-E817-4C7B-B670-4102E2DBDE36}
 */
public interface IMeasurement {
	/** @modelguid {01461FFA-2EEA-4764-86C9-C8AEDCCC85B8} */
    public Unit getUnit();

	/** @modelguid {908C0E6C-5AAD-4CC4-A5E2-9CB9028A2293} */
    public void setUnit(Unit unit);

	/** @modelguid {C74B1374-A3E2-419A-B672-A8E8EAE3F403} */
    public double getValue();

	/** @modelguid {A77395A7-0D7C-45B3-9673-86F991BCBD83} */
    public void setValue(double value);

	/** @modelguid {8B9BCA8E-75CD-4B32-ADE7-05563C76A0F1} */
    public IMeasurement add(IMeasurement measurement) throws QuantityConversionException;

	/** @modelguid {DE137EB0-E0CD-490F-A953-0CA6C9231B01} */
    public IMeasurement multiply(IMeasurement multiplier) throws QuantityConversionException;

	/** @modelguid {F2873131-103C-438A-8CF1-49C27D2150DC} */
    public boolean greaterThan(IMeasurement measurement) throws QuantityConversionException;

	/** @modelguid {BB208869-6AE8-4A2D-8EBD-1FCD4126CEA9} */
    public boolean lessThan(IMeasurement measurement) throws QuantityConversionException;

	/** @modelguid {D13D24EA-B739-45F3-B494-A04A04C8EC3E} */
    public boolean equals(IMeasurement measurement) throws QuantityConversionException;

	/** @modelguid {B4EAF75E-9849-4286-9EAC-EE11696B00D0} */
    public String toString();
}
