/* Generated by Together */

package mojo.km.units;
import java.lang.Exception;

/** @modelguid {57F5E48A-E162-498C-849D-6AA11CD1CF07} */
public class UnitNotFoundException extends Exception{
	/** @modelguid {D5DDC7D2-9D7D-45FB-8DAB-358D6A69FD5A} */
    public UnitNotFoundException() {
    }
}
