/* Generated by Together */

package mojo.km.units;
import java.io.Serializable;

/**
 * Responsible for knowing the unit of a given quantity (i.e. Length, Time, etc.)
 * @stereotype entity
 * @modelguid {6468A81E-057B-4765-A0B8-447E545319E2}
 */
public class Unit implements Serializable {
	/** @modelguid {6915FE30-F4C4-41B8-B6B2-069EA80A60AE} */
    public Unit(String aName){
        setName(aName);
        // default to zero; override this in subclass
        setPrecision(0);
    }

	/** @modelguid {AD02F96B-EEB5-42FC-B763-5DA433E800B2} */
    public String getName(){
            return name;
        }

	/** @modelguid {D92FFDE6-A5A0-492E-B54A-D85CFAD1EC01} */
    public void setName(String name){
            this.name = name;
        }

	/** @modelguid {BB77566E-4027-4670-A20E-10E6C2CEF305} */
    public int getSubUnits() {
        return subUnits;
    }

	/** @modelguid {B16FB351-0A88-4EE2-813B-729DBA358EAF} */
    public void setSubUnits(int subUnits) {
        this.subUnits = subUnits;
    }

	/** @modelguid {6D61F66F-71E3-4DA9-A47C-1662526B3D29} */
    public String getSeparator() {
        return separator;
    }

	/** @modelguid {2723CC10-42A3-4783-94E0-0137C39DB41A} */
    public void setSeparator(String separator) {
        this.separator = separator;
    }

	/** @modelguid {9DAA861D-F94C-46C4-B3D8-88B341D4E0AC} */
    public int getPrecision() {
        return precision;
    }

	/** @modelguid {FDBEEE55-B61C-4490-9283-BBEEB65DE5E5} */
    public void setPrecision(int precision) {
        this.precision = precision;
    }

	/** @modelguid {6FF08D1A-4393-4B0D-9996-88C5B7FA4CA0} */
    private int subUnits;
	/** @modelguid {3C45813F-0AD7-408A-BFC0-331A17C6CA81} */
    private String separator;
	/** @modelguid {83EBCEE5-F73A-47AC-92E8-4A8F37C136E5} */
    private String name;
    /** The precision required for a given unit 
     * @modelguid {4B8BF7A4-EAAA-42EA-B109-EB9848A03551}
     */
    private int precision;
}
