/* Generated by Together */

package messaging.appshell;

import mojo.km.messaging.ResponseEvent;
/**
 * Responsible for housing data that will be returned to boundry command DisplayFavoritesCommand
 *@author Noblestar
 *@version 1.0
 * @modelguid {2305129E-CEB7-42A4-ABFA-D8F092025339}
 */
public class DisplayFavoritesEvent extends ResponseEvent {
	/** @modelguid {7E09D4C7-FB10-4A84-B420-68122C4FBFBC} */
    public DisplayFavoritesEvent()
    {
        this.setTopic("dFavUI"); }

	/** @modelguid {96F1B1D9-2D78-4EB7-8369-FF32962A26D5} */
    public String getOID(){
            return OID;
        }

	/** @modelguid {B405CC6A-D928-4B12-BD37-3C39028CDE1F} */
    public void setOID(String OID){
            this.OID = OID;
        }

	/** @modelguid {4BCE0A9C-4D6C-4727-B810-A682CE869AF2} */
    public String getName(){
            return name;
        }

	/** @modelguid {AE11DC3B-CDEA-48FC-A441-B18FA77807DF} */
    public void setName(String name){
            this.name = name;
        }

	/** @modelguid {3895A9CA-5EF4-4C16-B8AD-213F30C25F36} */
    private String OID;
	/** @modelguid {02D26B94-B9D6-4BD5-AFB5-954FD6AE6606} */
    private String name;
}

