/* Generated by Together */

package messaging.appshell;

import mojo.km.messaging.ResponseEvent;

/** @modelguid {F0463F80-592C-453E-8BFC-E365D90A4EFB} */
public class DisplayFeatureUIEvent extends ResponseEvent
{

    /** @modelguid {7FB10BA4-403E-4391-900A-B1CA4C2D844D} */
    public DisplayFeatureUIEvent()
    {
        this.setTopic("dFeaUI");
    }

    /** @modelguid {B576D7BA-CDBB-4C9A-90AE-4266E39C7378} */
    public String getOID()
    {
        return OID;
    }

    /** @modelguid {C7884061-47D5-429E-B60E-6092F17EEC63} */
    public void setOID(String OID)
    {
        this.OID = OID;
    }

    /** @modelguid {BCA45680-2FAA-482F-A146-99A640E5A105} */
    public String getName()
    {
        return name;
    }

    /** @modelguid {DB3D1D4E-262D-4F4A-85E5-F0E0CD5CF01F} */
    public void setName(String name)
    {
        this.name = name;
    }

    /** @modelguid {ED11A691-EF92-49CC-AA06-34EDFDB8E5F0} */
    private String name;

    /** @modelguid {385C0F2D-163A-449E-BC24-E6B2F652FC0B} */
    private String OID;

}
