/* Generated by Together */

package mojo.km.messaging;

import java.io.Serializable;
/**
 * IInsertable is an interface which is implemented by all the Translate Events for the
 * FileImport functionality. Translate commands are used to translate general data from a
 * file to a module specific event. 
 *@author Anurag Srivastava
 * @modelguid {E5E55950-BF6E-4336-AB43-07A75889B73C}
 */

public interface IInsertable {
    /**
     * @param aObject 
     * @modelguid {B3A638B3-8924-4143-986B-99B3D9BDFBB7}
     */
    public void insertEvent(Serializable aObject);
}
