/* Generated by Together */

package mojo.km.messaging;

/**
 * Defines an interface for event to define a publish and subscribe topic. 
 * @modelguid {527100C5-7BB8-459D-88BA-2B653DB83449}
 */
public interface ITopic {
    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {5BDBBBB0-6081-4DA1-916D-36FEA65D77DE}
     */
    public String getTopic();

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {E036D7E0-327A-4E4F-8E50-35E55A4F12F9}
     */
    public void setTopic(String aService);

    /**
     *     Get hashkey use to filter on event listener
     *     @return hash code
     * @modelguid {38287512-8BC6-473D-B2E3-7A0A227E1AA3}
     */
    public String hashKey();
}
