/* Generated by Together */

package mojo.km.messaging;

/**
 *Responsible for defining user login event
 *@author Eric A Amundson
 *@version 1.0
 * @modelguid {FDD37170-6E06-4B29-B05E-5F591F6982E6}
 */
public class LoginRequest extends RequestEvent {

	public LoginRequest()
	{
	}

    /** @return user password. 
     * @modelguid {E190DDA8-89C6-4767-9734-BA6BB37DF20E}
     */
    public String getPassword() { return password; }

    /** @param password - value to be set for password. 
     * @modelguid {F4734059-9689-48CA-8C9B-4A6F94D8502A}
     */
    public void setPassword(String password) { this.password = password; }

    /** The password required to authenticate user. 
     * @modelguid {9D646657-402B-4367-963D-7574F7ED390F}
     */
    private String password;
}
