/* Generated by Together */

package mojo.km.messaging;

import mojo.km.config.MojoProperties;
import mojo.km.config.ServiceProperties;

/**
* Provides adapter implementation for topic interface
*
* @author Eric A Amundson
* @modelguid {6D3083C0-13F6-4FD3-A66C-4B3D0301CF0F}
**/
public class Topic implements ITopic {
	/** @modelguid {4FC0F985-1E68-4ED3-8374-947AAC4D34C4} */
    public Topic() {
    }

    /**
     * @param param
     * @param service 
     * @modelguid {78F0AE46-F878-40C8-8BAE-58C07D7ED49C}
     */
    public Topic(String param, String service) {
        topic = param;
        serviceName = service;
    }

	/** @modelguid {0AF762E7-ED13-4C7F-A19A-F65E74A23D89} */
    private String topic = "";
	/** @modelguid {7CECFF7F-3674-472A-B1C5-24D1426FCA2F} */
    private String serviceName;

    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {3C96624D-8733-4F10-93FA-D7F8F3455A11}
     */
    public String getTopic(){ return topic; }

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {02965E80-7FB7-4DAF-9AEA-C5EECB99C4F2}
     */
    public void setTopic(String aService){ this.topic = aService; }

    /**
     * Listener topic.
     *     @return hash code.
     * @modelguid {14B1EE3C-DAEA-41EB-BCFF-AA014A540327}
     */
    public String hashKey() {
        StringBuffer aStr = new StringBuffer(50);
        ServiceProperties lService = MojoProperties.getInstance().getService(serviceName);
        aStr.append(topic).append("::");
        if (lService != null) {
        	aStr.append(lService.getEventName());
        }
        return aStr.toString();
    }

    /**
     * @return 
     * @modelguid {EA793CE5-E9C1-4F1F-9CE0-6B73EE93CBAA}
     */
    public String getServiceName(){
            return serviceName;
        }

    /**
     * @param serviceName 
     * @modelguid {7B82EADA-6002-4D09-B713-1A7AFDE7D171}
     */
    public void setServiceName(String serviceName){
            this.serviceName = serviceName;
        }
}
