/* Generated by Together */

package mojo.ui.common;

/**
 * This table model will automatically register a ICommand listener on incoming mojo.km.messaging.IEvent's set to a the constructors parameters ITopic.
 * 
 * Rows added to the model should match incoming events bean spec.  The listener registered will use mojo.km.utilities.PropertyCopier to move information from incoming beans to the tables row.
 * @contextManagerName mojo.km.context.Default.DefaultContextManager
 * @requestDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @replyDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @asyncDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @queueDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @pubSubDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @debugMode false
 * @connectionPool false
 * @workflowEnabled false
 * @type Product Requirement 
 * @modelguid {8301CC0A-AFCB-4307-B4CA-C242F7C61071}
 */
public class DefaultTableModel extends TableMap {
}
