/* Generated by Together */

package mojo.ui.common;

/**
 * Implemented if a UI component is going to send IEvent to be cached for submission.
 * @contextManagerName mojo.km.context.Default.DefaultContextManager
 * @requestDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @replyDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @asyncDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @queueDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @pubSubDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @debugMode false
 * @connectionPool false
 * @workflowEnabled false 
 * @modelguid {5DE7BA4D-2761-4018-BFC0-AEB9CCB57239}
 */
public interface EventCacheable {
	/** @modelguid {40CFE0FD-B1F3-42BF-9A87-F9700B69D454} */
    public void setCache( java.util.Map cache );

	/** @modelguid {3B7AE32C-98CF-4017-9BE7-ACCFB5798971} */
    public void postEvent( mojo.km.messaging.IEvent event );
}
