/* Generated by Together */

package mojo.ui.common;

/** @modelguid {5CD9FFFD-494B-40A3-9C25-AA9922030641} */
public interface EventCreatorRow {
	/** @modelguid {92F55518-9B47-441D-8230-628D9483283D} */
    public mojo.km.messaging.IEvent getOutEvent();
}
