/* Generated by Together */

package mojo.ui.common;
import java.awt.event.MouseEvent;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentListener;
import java.awt.event.ComponentEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.AncestorEvent;
import javax.swing.JScrollPane;

/**
 * Integrates all of the ICommand, IEvent creation, and dispatch invocation.
 * @contextManagerName mojo.km.context.Default.DefaultContextManager
 * @requestDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @replyDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @asyncDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @queueDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @pubSubDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @debugMode false
 * @connectionPool false
 * @workflowEnabled false 
 * @modelguid {58B85D26-A4E4-4206-84B6-E0040515339F}
 */
public class IntegratedTable extends javax.swing.JTable implements EventCacheable {
	/** @modelguid {C22DA787-4A34-4DA7-A416-939A1E7071AE} */
    public IntegratedTable()
    {
        initGUI();
    }

	/** @modelguid {4AB5F076-3E30-4E3B-BABF-81F61AEDF49C} */
    public void setCache( java.util.Map cache) { this.cache = cache; }

	/** @modelguid {1EE11701-B515-4CAA-9296-8D679A93A3C3} */
    public void postEvent( mojo.km.messaging.IEvent event ) { cache.put(event, event); }

	/** @modelguid {03A7B705-855F-4A6E-BDFC-2FA0B87C1C43} */
    public void enableInsert() {
        if (insertEnable == false) {
            AddRow aRow = new AddRow();
            this.addMouseListener( aRow );
            this.getTableHeader().addMouseListener( aRow );
            insertEnable = true;
        }
    }

	/** @modelguid {740D4C90-FA35-482E-B61B-10EC484771B2} */
	public void initGUI()
    {
	    deleteItem = new JMenuItem();
	    insertItem = new JMenuItem();
	    insertDeleteMenu = new JPopupMenu();
	    insertDeleteMenu.setLabel("Insert - Delete");
	    insertDeleteMenu.add(insertItem);
	    insertDeleteMenu.add(deleteItem);
	    insertItem.setText("insert");
	    deleteItem.setText("delete");
	    insertDeleteMenu.addPopupMenuListener(
        new PopupMenuListener() {
            public void popupMenuCanceled(PopupMenuEvent e) { }
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) { insertDeleteMenuPopupMenuWillBecomeInvisible(e); }
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) { insertDeleteMenuPopupMenuWillBecomeVisible(e); }
        });
	    insertItem.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){insertItemActionPerformed(e);}});
	    deleteItem.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){deleteItemActionPerformed(e);}});
        this.addAncestorListener( new HandleVisiblity() );
    }

	/** @modelguid {232596A9-AD09-4DA3-BEF0-1DF99F413F34} */
    public void insertDeleteMenuPopupMenuWillBecomeVisible(PopupMenuEvent e) { }

	/** @modelguid {3FFF3F22-9989-4180-9051-0344FB77F21F} */
    public void insertDeleteMenuPopupMenuWillBecomeInvisible(PopupMenuEvent e) { }

	/** @modelguid {150DAB26-3DEB-41F2-9182-F60BBD80F7D4} */
    public void insertItemActionPerformed(ActionEvent e)
    {
		if (IntegratedTable.this.getModel() instanceof IntegratedTableModel) {
			IntegratedTableModel tModel = (IntegratedTableModel) IntegratedTable.this.getModel();
			tModel.setupRow();
		}
    }

	/** @modelguid {8270B621-0544-47C0-A398-DD72537A5F86} */
    public void deleteItemActionPerformed(ActionEvent e) { }

	/** @modelguid {682A9F0C-52E8-47FB-AC0F-CC216D61B87E} */
    class AddRow implements java.awt.event.MouseListener {
		/** @modelguid {C90C40FD-8A83-4D56-8109-3E74A3189C56} */
        public void mouseClicked(MouseEvent event) {
            if (event.isMetaDown()) {
				IntegratedTable.this.insertDeleteMenu.show( event.getComponent(), event.getX(), event.getY() );
                IntegratedTable.this.insertDeleteMenu.setVisible(true);
            }
        }

		/** @modelguid {083997B0-0A6A-4F55-9091-34910DE760F6} */
        public void mousePressed(MouseEvent event) {
        }

		/** @modelguid {A6A96C6A-06CA-4CB2-9E4F-189CF75B5404} */
        public void mouseReleased(MouseEvent event) {
        }

		/** @modelguid {EB9FB373-113E-4A0C-9511-73BEC57BB165} */
        public void mouseEntered(MouseEvent event) {
        }

		/** @modelguid {C0EF548F-F9DE-488E-8A35-349A61AC9D4F} */
        public void mouseExited(MouseEvent event) {
        }
    }

	/** @modelguid {E6B4616A-FB7B-43F0-B479-352DE98D5636} */
    class HandleVisiblity implements AncestorListener {


		/** @modelguid {C7E519A0-DB64-41C2-8061-3E1D3754C81B} */
        public void ancestorAdded(AncestorEvent event) {
        }

		/** @modelguid {2DDF6E0B-C45E-4178-A586-F405839E6BAB} */
        public void ancestorRemoved(AncestorEvent event) {
			if (IntegratedTable.this.getModel() instanceof IntegratedTableModel) {
				IntegratedTableModel tModel = (IntegratedTableModel) IntegratedTable.this.getModel();
                tModel.unregister();
            }
        }

		/** @modelguid {59FC3371-CB6F-4550-8063-50937142ECFB} */
        public void ancestorMoved(AncestorEvent event) {
        }
    }


	/** @modelguid {E9CBCE9A-1875-40BB-A5CC-681ABF6E2273} */
    private java.util.Map cache = null;
	/** @modelguid {EFFD4218-1177-48BD-BB58-9092A36BB027} */
    private boolean insertEnable = false;
	/** @modelguid {26B70B76-65F2-439E-BE7D-30A907A8A71C} */
    private JPopupMenu insertDeleteMenu;
	/** @modelguid {3451D1ED-B1CF-4347-8A88-87C3BB6233AB} */
    private JMenuItem insertItem;
	/** @modelguid {B64A3783-648E-4A90-A777-85AA1C85D94C} */
    private JMenuItem deleteItem;
	/** @modelguid {47DD794D-1223-4B50-AB1A-192F0DE0781C} */
    private JScrollPane jScrollPane1 = new JScrollPane();
}
