/* Generated by Together */

package mojo.ui.common;

import mojo.km.messaging.ITopic;

/** @modelguid {BDFECC7E-E3B0-4FD7-820C-EE3BC403B55A} */
public interface IPubSubComponent {

    /**
    * Implement to register all mojo event listeners to be implemented by app
    * component.
    * @param topic - which has the main filter for components specific events.
    * @modelguid {ADD59683-0942-4208-A42E-C4F3B95891AC}
    **/
	public void register( ITopic topic );

    /**
    * Implement to swap component listeners between topics.
    * @modelguid {90B87513-794A-44C6-916E-412A9A428F57}
    **/
    public void swap( ITopic oldTopic, ITopic newTopic);

    /**
    * Implement to unregister event lister on this topic
    * @modelguid {64269E1A-F5D6-468E-B108-223E341626BE}
    **/
    public void unregister( ITopic topic );
}
