/* Generated by Together */

package mojo.ui.common;

/**
 * Interface that defines components which have single valued components.
 * @contextManagerName mojo.km.context.Default.DefaultContextManager
 * @requestDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @replyDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @asyncDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @queueDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @pubSubDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @debugMode false
 * @connectionPool false
 * @workflowEnabled false 
 * @modelguid {7515D9EA-1058-4F31-B873-BCD236B5E3E8}
 */
public interface PropertyComponent {
	/** @modelguid {762DE58B-6EC3-4726-B563-AA9D77AF08D7} */
    public void setValue(Object value);
	/** @modelguid {D9530E54-7686-467F-8A5C-59AF803CF838} */
    public String getName();
	/** @modelguid {1140361A-D301-4AAE-AB3B-DA7683E61F34} */
    public void setName(String name);
	/** @modelguid {8EC6F18E-8F31-4027-B0A0-AF195A1776D0} */
    public void register();
	/** @modelguid {676B675A-B028-4C4A-AF99-25AFE03B3251} */
	public void unregister();
}
