/* Generated by Together */

package mojo.ui.common;

import mojo.km.messaging.ITopic;

import javax.swing.tree.*;
import java.awt.dnd.*;

/**
* Abstract class the define a swing JPanel that implement the IPubSubComponent interface.
* @author Eric A Amundson
* @modelguid {74CF77A4-A852-43E5-AF04-D542A95FDC8B}
**/
abstract public class PubSubTree extends javax.swing.JTree
    		implements IPubSubComponent, ITopic {

	/** @modelguid {9161C301-4606-419B-97C4-5B0D69896F4D} */
    public PubSubTree(ITopic topic) {
        setTopic(topic.getTopic());
        register(this);
    }

	/** @modelguid {50515DB9-C177-49E7-B97E-A54F16493434} */
    public PubSubTree(DefaultMutableTreeNode root) {
        super(root);
    }

	/** @modelguid {2543AC60-DA6B-4318-8B9D-3509361361F5} */
    public PubSubTree(ITopic topic, DefaultMutableTreeNode root) {
        super(root);
        setTopic(topic.getTopic());
        register(this);
    }

	/** @modelguid {78913EF8-5B27-4FEC-B80A-15B82A4B8B64} */
    public PubSubTree() {
    }

    /**
    * Implement to swap component listeners between topics.
    * @modelguid {5ECF1276-4A4A-4055-AAC2-8F1D07A05E7B}
    **/
    public void swap( ITopic oldTopic, ITopic newTopic)
    {
		unregister( oldTopic );
        setTopic( newTopic.getTopic() );
        register( newTopic );
    }

    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {3B2C32B2-F9F0-4838-9526-866ED27C8BEF}
     */
    public String getTopic(){ return topic; }

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {692EBB94-698E-4DAA-A2BF-E4C7A8678F9B}
     */
    public void setTopic(String topic){ this.topic = topic; }


	/** @modelguid {29C252BF-73F6-4234-AF4A-8FA3C5036AB0} */
    private String topic = "";
}

