/* Generated by Together */

package mojo.ui.common;
import mojo.km.messaging.ITopic;
/**
* Abstract class the define a swing JFrame that implement the IPubSubComponent interface.
* @author Eric A Amundson
* @modelguid {99A9047C-108B-49F4-9302-B44474D3604F}
**/

abstract public class PubSubFrame extends javax.swing.JFrame implements IPubSubComponent, ITopic {
	/** @modelguid {2B90106F-6B1F-40DB-A30A-58D863EA672E} */
	public PubSubFrame(ITopic topic) {
        setTopic(topic.getTopic());
        register(this);
    }

	/** @modelguid {CB0CFD91-8B81-4DE2-A09C-E311B970E6F7} */
    public PubSubFrame() {
    }

    /**
    * Implement to swap component listeners between topics.
    * @modelguid {E7C8A56D-0840-43A6-AB9B-C2E19482CCDD}
    **/
    public void swap( ITopic oldTopic, ITopic newTopic)
    {
		unregister( oldTopic );
        setTopic( newTopic.getTopic() );
        register( newTopic );
    }

    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {A5469217-3FFB-4A68-92B5-0BD0CF2224EB}
     */
    public String getTopic(){ return topic; }

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {76557C8C-C89A-4C26-B678-20B1A54E71A2}
     */
    public void setTopic(String topic){ this.topic = topic; }


	/** @modelguid {7F610473-9F39-4FC4-A6A3-E816EE99899B} */
    private String topic = "";
}








