/* Generated by Together */

package mojo.ui.common;

import java.awt.Frame;
import mojo.km.messaging.ITopic;
import javax.swing.JDialog;

/**
 * Abstract class the define a swing JPanel that implement the IPubSubComponent interface.
 * @author Eric A Amundson
 * @modelguid {151C9FD6-475C-4B06-9D71-7768647CC9A7}
 */
abstract public class PubSubDialog extends JDialog implements IPubSubComponent, ITopic
{
	/** @modelguid {81A772E1-8CE4-4709-8045-51886DC2BF36} */
    public PubSubDialog(Frame owner, boolean modal, ITopic topic)
    {
        super(owner, modal);
        setTopic(topic.getTopic());
        register(this);
    }
	/** @modelguid {DA633357-D06B-43AB-8CC1-D01E2B639215} */
    public PubSubDialog(Frame owner, boolean modal)
    {
        super(owner, modal);
    }
	/** @modelguid {57D4ADC5-C496-402E-9AA3-89F0678658EA} */
    public PubSubDialog(ITopic topic)
    {
        setTopic(topic.getTopic());
        register(this);
    }

	/** @modelguid {E8F24F6B-BAC6-40BC-AC06-69D4155A693E} */
    public PubSubDialog()
    {
    }

    /** Implement to swap component listeners between topics. 
     * @modelguid {03D2FE27-8C73-40B0-AB34-E0D1827D456D}
     */
    public void swap(ITopic oldTopic, ITopic newTopic)
    {
        unregister(oldTopic);
        setTopic(newTopic.getTopic());
        register(newTopic);
    }

    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {C0B3E833-7FC6-480E-94A8-E4E49F278E1C}
     */
    public String getTopic() { return topic; }

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {7396F580-ABEF-4F2F-A4CA-7FDE9C6C2B8D}
     */
    public void setTopic(String topic) { this.topic = topic; }

	/** @modelguid {660AA24F-692C-4980-842E-A780A1AB3840} */
    private String topic = "";
}
