/* Generated by Together */

package mojo.ui.common;

import mojo.km.messaging.ITopic;
import javax.swing.JTable;
/**
* Abstract class the define a swing JPanel that implement the IPubSubComponent interface.
* @author Eric A Amundson
* @modelguid {45A367EE-9831-41CA-BCF0-E630400DD87B}
**/
abstract public class PubSubTable extends JTable implements IPubSubComponent, ITopic {
	/** @modelguid {CFE95AAB-92CE-42E2-AF8E-27C61406A765} */
    public PubSubTable(ITopic topic) {
        setTopic(topic.getTopic());
        register(this);
    }

	/** @modelguid {0611E6EE-BDC8-4809-A548-367E2BA66F53} */
    public PubSubTable() {
    }

    /**
    * Implement to swap component listeners between topics.
    * @modelguid {F7CA0C7F-C084-493C-9764-C3AAE7A38983}
    **/
    public void swap( ITopic oldTopic, ITopic newTopic)
    {
		unregister( oldTopic );
        setTopic( newTopic.getTopic() );
        register( newTopic );
    }

    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {1788C0AA-6C3B-43C0-81FC-AEA4EFB63CB9}
     */
    public String getTopic(){ return topic; }

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {081FFC7A-6F65-4E3C-B6D8-79E7FDBEF7C0}
     */
    public void setTopic(String topic){ this.topic = topic; }

	/** @modelguid {B7C2457E-198F-43E1-9B78-3071B1B8D543} */
    private String topic = "";
}
