/* Generated by Together */

package mojo.ui.common;

import mojo.km.messaging.ITopic;
/**
* Abstract class the define a swing JPanel that implement the IPubSubComponent interface.
* @author Eric A Amundson
* @modelguid {CE7CBE99-8D87-4912-A2EB-BAEF3993B570}
**/
abstract public class PubSubPanel extends javax.swing.JPanel implements IPubSubComponent, ITopic {
	/** @modelguid {9C1EA5DA-4AEF-48BA-8509-E0F794353B1F} */
    public PubSubPanel(ITopic topic) {
        setTopic(topic.getTopic());
        register(this);
    }

	/** @modelguid {FEDB29CF-22F9-4AA6-82B9-3D3C92997422} */
    public PubSubPanel() {
    }

    /**
    * Implement to swap component listeners between topics.
    * @modelguid {D808F870-1D8B-46BE-AF9E-C07491E7A733}
    **/
    public void swap( ITopic oldTopic, ITopic newTopic)
    {
		unregister( oldTopic );
        setTopic( newTopic.getTopic() );
        register( newTopic );
    }

    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {7C29C08B-4F02-4677-A099-B81C070A79C9}
     */
    public String getTopic(){ return topic; }

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {C84A4F0F-9CEE-4309-9870-7F418F6D09B5}
     */
    public void setTopic(String topic){ this.topic = topic; }


	/** @modelguid {311B861C-8EDD-4120-85ED-8102C94A0718} */
    private String topic = "";
}
