/* Generated by Together */

package mojo.ui.common;

import javax.swing.JComboBox;
import mojo.km.messaging.ITopic;
import mojo.km.messaging.Topic;
import mojo.km.messaging.IEvent;
import mojo.km.dispatch.EventManager;
import mojo.km.context.ICommand;
import mojo.km.context.ContextManager;
import java.util.Iterator;

/**
 * @contextManagerName mojo.km.context.Default.DefaultContextManager
 * @requestDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @replyDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @asyncDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @queueDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @pubSubDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @debugMode false
 * @connectionPool false
 * @workflowEnabled false 
 * @modelguid {6E7C9392-C5F2-4A93-BB7A-AE4789F64512}
 */
abstract public class PubSubComboBox extends JComboBox implements IPubSubComponent, ITopic {

	/** @modelguid {5B2B532C-7ED1-4BB6-8FE6-7EC0F1556DE1} */
    protected String topic;
	/** @modelguid {1E1B6C9B-BD2C-4C99-9282-F47D43BDDD6F} */
	public PubSubComboBox(){}

	/** @modelguid {95C0428D-BEDC-4EE0-8A6B-388CCF6599FC} */
	public PubSubComboBox(ITopic topic) {
        setTopic(topic.getTopic());
        register(this);
    }

    /**
    * post the event being subscribed to
    * @modelguid {BCF7A96E-C8EC-4D3B-B760-1F9478C00BA0}
    */
    abstract public void postSubscribingEvent();

    //ITopic Implementations
	/** @modelguid {BB553C7E-E4CD-4D2B-99A3-464AC1241678} */
	public String getTopic() {
	    return topic;
	}
	/** @modelguid {88CC7A6F-F50F-4D36-96AA-4E4BAFDA9F8E} */
	public void setTopic(String topic) {
	    this.topic = topic;
	}
	/** @modelguid {BBA4D3C8-A42D-459E-8AFF-3D9DDCAE909E} */
	public String hashKey() {
	    return null;
	}
	//end ITopic Implementations

    //IPubSubComponent Implementations
	/** @modelguid {ACA759FF-F688-48FA-A536-795513396869} */
    public void register(ICommand com, IEvent event) {
		 ContextManager.currentContext().registerEventListener(com, event);
    }

	/** @modelguid {8959AB7C-D5E8-4234-BDC8-F8192A373A0D} */
    public void unregister(ICommand com, IEvent event) {
    }

	/** @modelguid {53E8B98A-2DC9-4EFC-A10E-E6C279251C54} */
    public void swap( ITopic oldTopic, ITopic newTopic) {
		unregister(oldTopic);
        setTopic(newTopic.getTopic());
        register(newTopic);
    }
    //end IPubSubComponent Implementations

}
