/* Generated by Together */

package mojo.ui.common;

import mojo.km.messaging.ITopic;
import javax.swing.JList;
/**
* Abstract class the define a swing JPanel that implement the IPubSubComponent interface.
* @author Eric A Amundson
* @modelguid {E21ECA40-FE10-4C17-915D-863126504A17}
**/
abstract public class PubSubList extends JList implements IPubSubComponent, ITopic {
	/** @modelguid {A064E3F9-7C8B-48CF-9CF9-9585F788F03A} */
		public PubSubList(ITopic topic) {
        setTopic(topic.getTopic());
        register(this);
    }

	/** @modelguid {ED4FE8FE-885F-4A0D-A223-1F95B6796C96} */
    public PubSubList() {
    }

    /**
    * Implement to swap component listeners between topics.
    * @modelguid {090CC74A-17FF-4E23-B4D7-A83E0412D67C}
    **/
    public void swap( ITopic oldTopic, ITopic newTopic)
    {
		unregister( oldTopic );
        setTopic( newTopic.getTopic() );
        register( newTopic );
    }

    /**
     *     Returns the topic event is set to.
     *     @return event topic.
     * @modelguid {1CCB49F3-BE26-459F-ABC0-8212AB196986}
     */
    public String getTopic(){ return topic; }

    /**
     *     Set the topic the event is to be associated with.
     *     @param aService - event topic
     * @modelguid {610B3D2F-7DB3-4173-8469-43E912F48483}
     */
    public void setTopic(String topic){ this.topic = topic; }


	/** @modelguid {85A2726E-DFFC-49A3-A181-8DE262B577CE} */
    private String topic = "";
}
