<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!-- 03/10/2008	 Aswin Widjaja - Create JSP -->
<!-- 08/22/2008  Debbie Williamson - Added validation -->
<!-- 04/02/2009  slin       - 58458 various UI fixes -->
<!-- 05/15/2009  LDeen      - 59577 remove mark EventName required -->
<!-- 06/18/2010  CShimek    - Activity 66039, revised Office Visit Date to input field w/o default value for Create flow -->
<!-- 06/22/2010  CShimek    - Activity 66106, undo changes for Activity 66039 -->
<!-- 06/25/2010  L Deen       Activity #66169 change to tinyMCECustomInitCasenote.js-->
<!-- 08/24/2011  RCapestani - Activity #71051 add code to display address and employment information  -->
<!-- 09/21/2011  RCapestani - Activity #71306 add code to display reschedule reason  -->
<!-- 09/29/2011  RCapestani - Activity #71306 add code to require reschedule reason text -->
<!-- 01/19/2012  RYoung     - Defect #72412 CSCD: Calendar - Field Validation missing on Event Date. -->
<!-- 02/23/2012  RCapestani - Activity #71306 add alert when event is rescheduled and date is in the past  -->
<!-- 04/12/2012  TSVines    - 72079 added the class=buttonBar" to the <tr> -->

<!--TAG LIBRARIES NEEDED FOR STRUTS -->
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/jims2-presentation.tld" prefix="jims" %>
<%@page import="naming.UIConstants"%>
<%@page import="naming.PDCodeTableConstants"%>
<!-- TAB LIBRARIES NEEDED FOR MOJO -->
<%@ taglib uri="/WEB-INF/msp.tld" prefix="msp" %>
<!--LOCALE USED FOR INTERNATIONALIZATION-NOT USED YET -->


<!--BEGIN HEADER TAG-->
<head>
<msp:nocache />
<%-- Checks to make sure if the user is logged in. --%>
<%--msp:login / --%>
<meta http-equiv="Content-Language" content="en-us">
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1" %>
<META http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<META name="GENERATOR" content="IBM WebSphere Studio">
<META http-equiv="Content-Style-Type" content="text/css">

<!-- STYLE SHEET LINK -->
<link rel="stylesheet" type="text/css" href="/<msp:webapp/>css/base.css" />
<html:base />
<title><bean:message key="title.heading" /> - csCalendar - officeVisitCreateUpdate.jsp</title>

<%--html:javascript formName="officeVisitCreateUpdate"/--%>

<script type='text/javascript' src="/<msp:webapp/>js/timeout.js"></script>
<script type="text/javascript" src="/<msp:webapp/>js/CalendarPopup.js"></script>
<script type="text/javascript" src="/<msp:webapp/>js/AnchorPosition.js"></script>
<script type="text/javascript" src="/<msp:webapp/>js/common_supervision_util.js"></script>
<script type="text/javascript" src="/<msp:webapp/>js/customStrutsBasedValidation.js"></script>
<script type="text/javascript" src="/<msp:webapp/>js/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="/<msp:webapp/>js/tinyMCECustomInitCasenote.js"></script>
				
<script type="text/javascript">
  <%-- Please leave Purpose and Narrative fields at 7000 even though arg1 is 3500.  It needs to be 7000 to accommodate the hidden characters generated by TinyMCE. DAW --%>   	      
	function validateField(theForm){		  
		clearAllValArrays();		      
		var fld = document.getElementsByName("currentOfficeVisit.eventDateStr");
		if (fld[0] != null){
			customValRequired("currentOfficeVisit.eventDateStr", "<bean:message key='errors.required' arg0='Office Visit Date'/>","");
			addMMDDYYYYDateValidation("currentOfficeVisit.eventDateStr","Office Visit Date must be in date format (mm/dd/yyyy). ");
		}
		addAlphaNumericNoFirstSpacewSymbolsValidation("currentOfficeVisit.eventName", "<bean:message key='errors.alphanumericWSymbols2' arg0='Event Name'/>","");
		customValMaxLength("currentOfficeVisit.eventName","<bean:message key='errors.maxlength' arg0='Event Name' arg1='20'/>","20");
		add12HrTimeValidation("currentOfficeVisit.startTime","Start Time is not in proper 12 hour format, ie 03:15","");
		add12HrTimeValidation("currentOfficeVisit.endTime","End Time is not in proper 12 hour format, ie 03:15","");
		customValMinLength("currentOfficeVisit.altPhone.areaCode","<bean:message key='errors.minlength' arg0='Alternate Phone Area Code' arg1='3'/>","3");
		addNumericValidation("currentOfficeVisit.altPhone.areaCode", "<bean:message key='errors.numeric' arg0='Alternate Phone Area Code'/>","");
		customValMinLength("currentOfficeVisit.altPhone.prefix","<bean:message key='errors.minlength' arg0='Alternate Phone Prefix' arg1='3'/>","3");
		addNumericValidation("currentOfficeVisit.altPhone.prefix", "<bean:message key='errors.numeric' arg0='Alternate Phone Prefix'/>","");
		customValMinLength("currentOfficeVisit.altPhone.fourDigit","<bean:message key='errors.minlength' arg0='Alternate Phone Four Digit' arg1='4'/>","4");
		addNumericValidation("currentOfficeVisit.altPhone.fourDigit", "<bean:message key='errors.numeric' arg0='Alternate Phone Four Digit'/>","");
		addDefinedTinyMCEFieldMask("currentOfficeVisit.purpose","Purpose Text cannot have % or _ entries","");
		customValMinLength("currentOfficeVisit.purpose","<bean:message key='errors.minlength' arg0='Purpose' arg1='1'/>","1");
		customValMaxLength("currentOfficeVisit.purpose","<bean:message key='errors.maxlength' arg0='Purpose' arg1='3500'/>","7000");
		fld = document.getElementsByName("currentOfficeVisit.rescheduleReason");
		if (fld[0] != null){
			customValRequired("currentOfficeVisit.rescheduleReason", "<bean:message key='errors.required' arg0='Rescheduled Reason'/>","");
			addDefinedTinyMCEFieldMask("currentOfficeVisit.rescheduleReason","Purpose Text cannot have % or _ entries","");
			customValMinLength("currentOfficeVisit.rescheduleReason","<bean:message key='errors.minlength' arg0='Rescheduled Reason' arg1='1'/>","1");
			customValMaxLength("currentOfficeVisit.rescheduleReason","<bean:message key='errors.maxlength' arg0='Rescheduled Reason' arg1='3500'/>","7000");
		}	
		return validateCustomStrutsBasedJS(theForm);
	}
		  
	function validateResults(theForm) {
		clearAllValArrays();		      
		trimCasenote('currentOfficeVisit.narrative');
		customValRequired("currentOfficeVisit.outcomeCd", "<bean:message key='errors.required' arg0='Outcome'/>","");
		customValRequired("currentOfficeVisit.narrative", "<bean:message key='errors.required' arg0='Narrative'/>","");
		customValMaxLength("currentOfficeVisit.narrative","<bean:message key='errors.maxlength' arg0='Narrative' arg1='3500'/>","7000");
		addDefinedTinyMCEFieldMask("currentOfficeVisit.narrative","Narrative Text cannot have % or _ entries","");
		if (validateCustomStrutsBasedJS(theForm) && validateForBROnly(document.getElementsByName('currentOfficeVisit.narrative')[0].value, 'Narrative is required')){
			return true;
		}else {
			return false;
		}
	}
	function setCursor(){
		var fld = document.getElementsByName("currentOfficeVisit.eventDateStr");
		if (fld[0] != null){
			fld[0].focus();
		} else {
			fld = document.getElementsByName("currentOfficeVisit.eventName");
			if (fld[0] != null){
				fld[0].focus();
			}		
		} 
	}
	function flipText( idOfTD, textToSet ){
		if (document.getElementById( idOfTD ).innerHTML.indexOf("Address") > 0)
		{
			if (document.getElementById( idOfTD ).innerHTML == "View Address")
			{
				document.getElementById( idOfTD ).innerHTML = "Hide Address" ;
				show("addressRow", 1, "row")
			}else {
				document.getElementById( idOfTD ).innerHTML = "View Address" ;
				show("addressRow", 0)
			}
		}else if (document.getElementById( idOfTD ).innerHTML.indexOf("Employment") > 0)
		{
			if (document.getElementById( idOfTD ).innerHTML == "View Employment")
			{
				document.getElementById( idOfTD ).innerHTML = "Hide Employment" ;
				show("employmentRow", 1, "row")
			}else 
			{
				document.getElementById( idOfTD ).innerHTML = "View Employment" ;
				show("employmentRow", 0)
			}
		}
	}
	
	//this function confirms that the user wants to create an event in the past
	function checkBackDate(theForm){
		var dateFld = document.getElementsByName("currentOfficeVisit.eventDateStr");
		var theDate = new Date();
		if ( dateFld[0] != null ){
			
			var theEventDate = new Date (dateFld[0].value);
    		var sub5Year = theDate.getFullYear()-5;
			var sub5dateStr = (theDate.getMonth() + "/" + theDate.getDate() + "/" + sub5Year);
			var newSub5Date = new Date( sub5dateStr );

			if ( theEventDate <  newSub5Date ){
				
				alert( "Event Date cannot be more than 5 years previous to current date.\nValid date format is MM/dd/yyyy" );
				dateFld[0].focus();
				return false;
			}
			
			var plus5Year = theDate.getFullYear()+5;
			var plus5dateStr = (theDate.getMonth() + "/" + theDate.getDate() + "/" + plus5Year);
			var newPlus5Date = new Date( plus5dateStr );

			if ( theEventDate >  newPlus5Date ){
				
				alert( "Event Date cannot be more than 5 years to the future of current date.\nValid date format is MM/dd/yyyy" );
				dateFld[0].focus();
				return false;
			}
		 	
		 	var theMonth = theDate.getMonth()+1;
			var theDay = theDate.getDate();
			var theYear = theDate.getYear();
			if (theMonth < 10){
					theMonth = "0"+theMonth;
				}
				if (theDay < 10){
					theDay = "0"+theDay;
				}

			 var dateStr = (theMonth + "/" + theDay + "/" + theYear);
			 var theCurrentDate = new Date(dateStr);
			if (theEventDate <  theCurrentDate){
				return confirm("Event Date is in the past.\nClick Ok if you want to continue.")
			}
		}		
		return true;
	}
	
</script>
</head>
<body topmargin="0" leftmargin="0" onload="setCursor()">
		<html:form action="/displayCSOVDetails" target="content">
			<div align="center">
				<table width="98%" border="0" cellpadding="0" cellspacing="0" >
					<tr>
						<td valign="top"><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
					</tr>
					<tr>
						<td valign="top">
							<table width="100%" border="0" cellpadding="0" cellspacing="0" >
								<tr>
									<td valign="top">
										<tiles:insert page="../../../common/commonSupervisionTabs.jsp" flush="true">
											<tiles:put name="tab" value="caseloadTab"/>
										</tiles:insert>	
									</td>
								</tr>
								<tr>
									<td bgcolor="#6699FF"><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
								</tr>
							</table>
							<table width="100%" border="0" cellpadding="0" cellspacing="0" class="borderTableBlue">								
								
								<tr>
									<td><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
								</tr>
								<tr>
									<td align="center">
										<!--header start-->
										<tiles:insert page="../../../common/superviseeHeader.jsp" flush="true">
										</tiles:insert>	
										<!--header end-->
									</td>
								</tr>
								<tr>
									<td valign="top" align="center">										
										<!--casefile tabs start-->
										<table width="98%" border="0" cellpadding="0" cellspacing="0" >
											<tr>
												<td><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
											</tr>
											<tr>
												<td valign="top">
													<!--tabs start-->
													<tiles:insert page="../../../common/caseloadCSCDSubTabs.jsp" flush="true">
														<tiles:put name="tab" value="CalendarTab"/> 
													</tiles:insert>	
													<!--tabs end-->
												</td>
											</tr>
											<tr>
												<td bgcolor="#33cc66"><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
											</tr>
										</table>
										<table width="98%" border="0" cellpadding="0" cellspacing="0" class="borderTableGreen">
											<tr>
												<td><img src="/<msp:webapp/>images/spacer.gif" height="5"></td>
											</tr>
											<tr>
												<td valign="top" align="center">
													<!-- BEGIN HEADING TABLE -->
													<table width="100%">
														<tr>
															<td align="center" class="header">CSCD - 
																
																<logic:equal name="csCalendarOVForm" property="activityFlow" value="create">
																	<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|4">
																	<bean:message key="prompt.create" />
																</logic:equal>
																<logic:equal name="csCalendarOVForm" property="activityFlow" value="update">
																	<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|10">
																	<bean:message key="prompt.update" />
																</logic:equal>
										
																<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
																	<input type="hidden" name="helpFile" value="commonsupervision/CSCD_Calendar/CSCD_Calendar.htm#|8">
																	Reschedule
																</logic:equal>
																<bean:message key="prompt.officeVisit" />
															</td>
														</tr>
													</table>	
													<!-- BEGIN CONFIRMATION TABLE -->
													
													<table width="98%" border="0" cellpadding="2" cellspacing="1">
														<tr>
															<td class="confirm"><bean:write name="csCalendarOVForm" property="confirmMsg" /></td>
														</tr>
													</table>
													<!-- END CONFIRMATION TABLE -->
													<!-- BEGIN INSTRUCTION TABLE -->
													<div class="instructions"><ul><li>Enter required fields and click Submit.</li></ul></div>												
													<div class="required"><bean:message key="prompt.4.diamond"/><bean:message key="prompt.requiredFieldsInstruction"/>&nbsp;&nbsp;&nbsp;*All date fields must be in the format of mm/dd/yyyy.</div>
													<div class="spacer"></div>													
													<!-- END INSTRUCTION TABLE -->
													<!-- BEGIN DETAIL TABLE -->
													<table align="center" width='98%' cellpadding="2" cellspacing="0" class="borderTableBlue">
														<tr class="detailHead">
															<td><bean:message key="prompt.officeVisit"/> <bean:message key="prompt.info"/></td>															
															<td align="right">
																<a href="javascript:flipText('vAddress', 'View Address')" id="vAddress">Hide Address</a> | <a href="javascript:flipText('vEmployment', 'View Employment')" id="vEmployment">Hide Employment</a> | 
																<a href="javascript:openWindow('/<msp:webapp/>displayComplianceConditions.do?submitAction=Link&superviseeId=<bean:write name='csCalendarOVForm' property='currentOfficeVisit.superviseeId'/>')" class=blackSubNav>View Conditions</a>
															</td>
														</tr>
														<tr>
															<td colspan="2">
																<table width='100%' cellpadding="2" cellspacing="1">
																	<tr>
																		<td class="formDeLabel" nowrap>
																			<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
																				<bean:message key="prompt.4.diamond"/>
																			</logic:equal>
																			<logic:notEqual name="csCalendarOVForm" property="activityFlow" value="reschedule">
																				<logic:equal name="csCalendarOVForm" property="altFlow" value="<%=UIConstants.YES%>">
																					<bean:message key="prompt.4.diamond"/>
																				</logic:equal>
																			</logic:notEqual>		
																			
																			<bean:message key="prompt.officeVisit" /> <bean:message key="prompt.date" /></td>
																		<td class="formDe">
																		
																		<logic:notEqual name="csCalendarOVForm" property="activityFlow" value="reschedule">
																			<logic:notEqual name="csCalendarOVForm" property="altFlow" value="<%=UIConstants.YES%>">
																				<bean:write name="csCalendarOVForm" property="currentOfficeVisit.eventDate" formatKey="date.format.mmddyyyy"/>
																			</logic:notEqual>
																		</logic:notEqual>
																		
																		<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
																			<%-- Calendar popup javascript --%> 
																			<html:text property="currentOfficeVisit.eventDateStr" size="10" maxlength="10" />
																				<script type="text/javascript" id="js1">
																					var cal1 = new CalendarPopup();
																					cal1.showYearNavigation();
																				</script>
																			<A HREF="#" onClick="cal1.select(document.forms[0]['currentOfficeVisit.eventDateStr'],'anchor1','MM/dd/yyyy'); return false;"
																				NAME="anchor1" ID="anchor1" border="0"><bean:message key="prompt.4.calendar" /></A>																				
																		</logic:equal>
																		<%-- this should only be true when user selects finish and Schedule Next button on Office Visit Results Summary --%>
																		<logic:notEqual name="csCalendarOVForm" property="activityFlow" value="reschedule">
																			<logic:equal name="csCalendarOVForm" property="altFlow" value="<%=UIConstants.YES%>">
																				<%-- Calendar popup javascript --%> 
																				<html:text property="currentOfficeVisit.eventDateStr" size="10" maxlength="10" />
																					<script type="text/javascript" id="js1">
																						var cal1 = new CalendarPopup();
																						cal1.showYearNavigation();
																					</script>
																				<A HREF="#" onClick="cal1.select(document.forms[0]['currentOfficeVisit.eventDateStr'],'anchor1','MM/dd/yyyy'); return false;"
																					NAME="anchor1" ID="anchor1" border="0"><bean:message key="prompt.4.calendar" /></A>
																				<bean:define id="checkDate" value="Y" />																					
																			</logic:equal>
																		</logic:notEqual>
																		</td>																						
																		<td class="formDeLabel" nowrap><bean:message key="prompt.eventName"/></td>
																		<td class="formDe">
																			<html:text property="currentOfficeVisit.eventName" size="20" maxlength="20"/>
																		</td>																						
																	</tr>
																	<tr>
																		<td class="formDeLabel" nowrap><bean:message key="prompt.startTime" /></td>
																		<td class="formDe">
																          <html:text name="csCalendarOVForm" size="6" maxlength="5" property="currentOfficeVisit.startTime"/>
																             <html:select name="csCalendarOVForm" property="currentOfficeVisit.AMPMId1">
																	           <html:option value="AM">AM</html:option>
																	           <html:option value="PM">PM</html:option>
																           </html:select> 																
																		</td>
																		<td class="formDeLabel" nowrap><bean:message key="prompt.endTime"/></td>
																		<td class="formDe">
																			<html:text name="csCalendarOVForm" size="6" maxlength="5" property="currentOfficeVisit.endTime"/>
																             <html:select name="csCalendarOVForm" property="currentOfficeVisit.AMPMId2">
																	           <html:option value="AM">AM</html:option>
																	           <html:option value="PM">PM</html:option>
																           </html:select>
																		</td>
																	</tr>
																	<tr>
																		<td class="formDeLabel"><bean:message key="prompt.supervisee"/> <bean:message key="prompt.phone"/></td>
																		<td class="formDe"><bean:write name="csCalendarOVForm" property="currentOfficeVisit.superviseePhone.formattedPhoneNumber"/></td>
																		<td class="formDeLabel">Alternate <bean:message key="prompt.phone"/></td>
																		<td class="formDe">
																			<html:text property="currentOfficeVisit.altPhone.areaCode" size="3" onkeyup="return autoTab(this, 3);"/>
																			-
																			<html:text property="currentOfficeVisit.altPhone.prefix" size="3" onkeyup="return autoTab(this, 3);"/>
																			-
																			<html:text property="currentOfficeVisit.altPhone.fourDigit" size="4" maxlength="4" />
															
																		</td>
																	</tr>
																	<tr id="addressRow">
																		<td class="formDeLabel"><bean:message key="prompt.address"/></td>
																		<td colspan="3" class="formDe"><bean:write name="superviseeForm" property="superviseeStreetNumber"/> <bean:write name="superviseeForm" property="superviseeStreetName"/><logic:notEmpty  name="superviseeForm" property="superviseeStreetName"></logic:notEmpty> <logic:notEmpty  name="superviseeForm" property="superviseeApartmentNumber"> <bean:message key="prompt.aptSuite"/> <bean:write name="superviseeForm" property="superviseeApartmentNumber"/><br> </logic:notEmpty>
																			<bean:write name="superviseeForm" property="superviseeCity"/><logic:notEmpty  name="superviseeForm" property="superviseeCity">, </logic:notEmpty><bean:write name="superviseeForm" property="superviseeState"/> <bean:write name="superviseeForm" property="superviseeZipCode"/> <logic:notEmpty  name="superviseeForm" property="superviseeZipCode"><br> </logic:notEmpty>
																		<%-- 	 <a href=# disabled>Update Address</a> --%>
																		</td>
																	</tr>
																	<tr id="employmentRow">
																		<td class="formDeLabel"><bean:message key="prompt.employment"/></td>
																		<td colspan="3" class="formDe"><bean:write name="superviseeForm" property="employerName"/><logic:notEmpty name="superviseeForm" property="employePhoneNum">, <bean:write name="superviseeForm" property="employePhoneNum"/></logic:notEmpty><logic:notEmpty name="superviseeForm" property="employerOccupation">, <bean:write name="superviseeForm" property="employerOccupation"/></logic:notEmpty> 
																		<%--     <a href=# disabled>Update Employment</a> --%>
																		</td>
																	</tr>
																	<tr>
																		<td class="formDeLabel" colspan="4">Purpose of <bean:message key="prompt.officeVisit"/></td>
																	</tr>
																	<style>
																		.mceEditor{
																		width: "100%";
																		height: "150"
																		}
																	</style>
																	<tr class="formDe">
																		<td colspan="4" align="center">
																		  <bean:define id="agencyId" name="csCalendarOVForm" property="userAgency"/>
																			<html:textarea styleClass="mceEditor" style="width:100%" rows="12" property="currentOfficeVisit.purpose"/>
																		   <tiles:insert page="../../../common/spellCheckButtonTile.jsp" flush="false">
																	         <tiles:put name="agencyCode"><%=agencyId%></tiles:put>
																            </tiles:insert>	
																           
																		</td>
																	</tr>
																	<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">	
																		<tr>
																			<td class="formDeLabel" colspan="4"><bean:message key="prompt.4.diamond"/> <bean:message key="prompt.rescheduledReason"/> - <bean:message key="prompt.casenote"/></td>
																		</tr>
																		<style>
																			.mceEditor{
																			width: "100%";
																			height: "150"
																			}
																		</style>
																		<tr class="formDe">
																			<td colspan="4" align="center">
																			  <bean:define id="agencyId" name="csCalendarOVForm" property="userAgency"/>
																				<html:textarea styleClass="mceEditor" style="width:100%" rows="12" property="currentOfficeVisit.rescheduleReason"/>
																			   <tiles:insert page="../../../common/spellCheckButtonTile.jsp" flush="false">
																		         <tiles:put name="agencyCode"><%=agencyId%></tiles:put>
																	            </tiles:insert>	
																	           
																			</td>
																		</tr>
																	</logic:equal>
																	<logic:equal name="csCalendarOVForm" property="currentOfficeVisit.status" value="C">
																		<tr>
																			<td class="formDeLabel"><bean:message key="prompt.4.diamond"/><bean:message key="prompt.outcome"/></td>
																			<td class="formDe" colspan="3">
																				<html:select name="csCalendarOVForm" property="currentOfficeVisit.outcomeCd">
																					<html:option value=""><bean:message key="select.generic"/></html:option>
																					<html:optionsCollection name="csCalendarOVForm" property="filteredOVOutcomeList" value="supervisionCode" label="description"/>
																				</html:select>
																				
																			</td>
																		</tr>
																		
																		<tr>
																			<td class="formDeLabel" colspan="4"><bean:message key="prompt.4.diamond"/><bean:message key="prompt.narrative"/></td>
																		</tr>
																		<style>
																			.mceEditor{
																			width: "100%";
																			height: "150"
																			}
																		</style>
																		<tr class="formDe">
																			<td colspan="4" align="center">
																				<html:textarea styleClass="mceEditor" style="width:100%" rows="12" property="currentOfficeVisit.narrative"/>
																			</td>
																		</tr>
																	</logic:equal>
																</table>
															</td>
														</tr>
													</table>
													<!-- BEGIN DETAIL TABLE -->
													<!-- BEGIN BUTTON TABLE -->
													<table border="0" width="100%">
														<tr class="buttonBar">
															<td align="center">
																<logic:empty name="csCalendarOVForm" property="confirmMsg">
																	<html:submit property="submitAction"><bean:message key="button.back" /></html:submit>
																</logic:empty>																
																<logic:equal name="csCalendarOVForm" property="activityFlow" value="reschedule">
																    <html:submit property="submitAction" onclick="return (myTinyMCEFix() && validateField(this.form) && checkBackDate(this.Form))"><bean:message key="button.next" /></html:submit>
																</logic:equal>
																<logic:notEqual name="csCalendarOVForm" property="currentOfficeVisit.status" value="C">
																    <logic:notEqual name="csCalendarOVForm" property="activityFlow" value="reschedule">
															      		<html:submit property="submitAction" onclick="return (myTinyMCEFix() && validateField(this.form) && checkBackDate(this.form))"><bean:message key="button.next" /></html:submit>
																    </logic:notEqual>
																</logic:notEqual>
																<logic:equal name="csCalendarOVForm" property="currentOfficeVisit.status" value="C">
																    <html:submit property="submitAction" onclick="return (myTinyMCEFix() && checkBackDate(this.form) && validateField(this.form) && validateResults(this.form))"><bean:message key="button.next" /></html:submit>
																</logic:equal>        
																<html:submit property="submitAction"><bean:message key="button.cancel" /></html:submit>
															</td>
														</tr>
													</table>
													<!-- END BUTTON TABLE -->
												</td>
											</tr>
										</table><br>
									</td>
								</tr>
							</table><br></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
	<br>
</html:form>
	<div align="center"><script type="text/javascript">renderBackToTop()</script></div>
</body>
</html:html>
