/*
 * Created on Dec 29, 2006
 */
package naming;

/**
 * @author mchowdhury
 */
public class PDTaskConstants
{			
	public static final String SUBMITTED_STATUS_ID = "S";
	public static final String CREATE_TASK_ACTIVATE_CASEFILE = "JC.JUVENILECASEWORK.ACTIVATECASEFILE";
	public static final String CREATE_TASK_REVIEW_BENEFITS_ASSESSMENT = "JC.JUVENILECASEWORK.REVIEWBENEFITSASSESSMENT";
	public static final String SP_REFERRAL_TASK = "CS.PRGREFERRAL.REFERRALUPDATE";
	public static final String SP_DOCUMENT_ATTENDANCE_TASK = "JC.SERVICEEVENT.DOCUMENTATTENDANCE";
	public static final String JPO_REFERRAL_TASK = "JC.PRGREFERRAL.REFERRALUPDATE";
	public static final String CASEFILEACTIVATE_FAMILY_UPDATE = "JC.CASEFILEACTIVATE.FAMILYUPDATE";
	public static final String MJCW_JPO_OVERDUE_INTERVIEWNOTIFICATION = "MJCW.JPO.OVERDUE.INTERVIEWNOTIFICATION";
	public static final String MJCW_CLM_OVERDUE_INTERVIEWNOTIFICATION = "MJCW.CLM.OVERDUE.INTERVIEWNOTIFICATION";
	public static final String MJCW_JPO_OVERDUE_COMMUNITYSUPERVISION = "MJCW.JPO.OVERDUE.COMMUNITYSUPERVISION";
	public static final String MJCW_CLM_OVERDUE_COMMUNITYSUPERVISION = "MJCW.CLM.OVERDUE.COMMUNITYSUPERVISION";
	public static final String MJCW_JPO_OVERDUE_DEFERREDADJUDICATION = "MJCW.JPO.OVERDUE.DEFERREDADJUDICATION";	
	public static final String MJCW_JPO_PRECOURT_INTERVIEW = "MJCW.JPO.PRECOURT.INTERVIEW";
	
}
