/* Generated by Together */

package mojo.km.transaction;

/**
 * Defines interface for persistent object transaction management.  Does not define implementation of storage resource. 
 * @modelguid {E1DA836A-E409-449A-BA23-1CB4ADF2FCF9}
 */
public interface ITransactionManager {
    /**
     * Commit all changes to persistent object to storage resource. 
     * @modelguid {2B41FCEB-750A-46A2-9F18-60580E2521DE}
     */
    public void commit();

	/** @modelguid {F6E19B63-28DE-4AAF-B6FB-A5EC1DC18A43} */
    public void rollback();

	/** @modelguid {E10479C9-2213-4D44-A90F-AE4AB96E6512} */
    public void addUpdated(mojo.km.persistence.PersistentObject persistentObj);

	/** @modelguid {E0245B2C-E773-4B38-9915-586BCB0FBC9C} */
	public java.util.Iterator retrieve(mojo.km.persistence.PersistentObject persistentObj, mojo.km.messaging.IEvent anEvent);

}
