/* Generated by Together */

package mojo.es.reporting.reportrequests;

import java.util.Vector;

/**
 * @stereotype control
 * @serverName reportwriter
 * @eventPackage mojo.messaging.reportrequestevents
 * @queueDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @projectClass
 * @contextManagerName mojo.km.context.Default.DefaultContextManager
 * @dbPassword
 * @TransactionGroups
 * @MaxServers
 * @DataSource
 * @LastAccessed 0
 * @requestDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @BuildTUXEDOConfig
 * @DriverClass
 * @connectionPool false
 * @debugMode false
 * @serverUserID
 * @xaDataSourceClassName
 * @LoginCallback
 * @serverPassword
 * @pubSubDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @ClientPubSub mojo.km.dispatch.Multicast.MCPubSubStrategy
 * @serverURL
 * @MinServers
 * @dbURL
 * @httpURL
 * @asyncDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @Context mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @RequestReply mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @workflowEnabled false
 * @dbUserID
 * @projectPath
 * @replyDispatch mojo.km.dispatch.CurrentContext.CurrentContextStrategy
 * @licensePath
 * @modelguid {F247DCE1-3D13-4E5D-A613-DEBD69E48B4F}
 */
public class ReportRequestController {
    /**
     * @stereotype design
     * @serviceName requestReport
     * @modelguid {9F292A67-4FA5-4D3D-9F71-EFB769A90E02}
     */
    public void reportRequest(String replyEvent, String replyTopic, Vector reportData) { }
}
