/* Generated by Together */

package mojo.km.rulemanagement;

import java.util.Iterator;
import mojo.km.messaging.IEvent;

/**
 * Defines an interface for a any object to implement that require processing on its rules.
 * @author Eric A Amundson
 * @modelguid {D38AC2A0-4BC6-4B06-887D-A2DB66373215}
 */
public interface IEntityObject {
    /** @link dependency */

    /*#IEntityObject lnkIBusinessObject;*/

    /**
     * Executes all of the Rules for a given service.  A RuleException is thrown
     * from this method if a RuleException is caught from a Rule's execute method.
     * The method continues processing if a RuleException is caught, each subsequent
     * RuleException is put into the initial RuleException's list of RuleExceptions.
     * @param service The service to which the Rules are mapped.
     * @exception RuleException if any Rule throws a RuleException.
     * @return IEvent The return Event.
     * @modelguid {F99C6274-26A9-49E6-AFC3-D6B3E386976D}
     */
    public IEvent processRules(String service) throws RuleException;

    /**
     * Adds a Rule to the list of Rules for the given service.
     * @param service The service to which the Rules are mapped.
     * @param rule The Rule to be added.
     * @modelguid {43C7D1F9-50D6-4F74-AEBE-71AFCEAF5205}
     */
    public void insertRule(String service, IRule rule);

    /**
     * Removes a Rule from the list of Rules for the given service.
     * @param service The service to which the Rules are mapped.
     * @param rule The Rule to be removed.
     * @modelguid {BD5DCB4E-1051-47A5-8B35-9A9020517014}
     */
    public void deleteRule(String service, IRule rule);

    /**
     * Clears the list of Rules for the given service.
     * @param service The service to which the Rules are mapped.
     * @modelguid {0467E0E4-F1B9-4FA9-A298-FDA56AB8DF3F}
     */
    public void clearRules(String service);

    /**
     * Returns the list of Rules for the given service.
     * @param service The service to which the Rules are mapped.
     * @return Iterator An Iterator over the list of Rules for the given service.
     * @modelguid {C2D3957A-D50B-4B1B-B677-B1AAB04DB0F7}
     */
    public Iterator getRules(String service);
}
