/* Generated by Together */

package mojo.km.rulemanagement;

import mojo.km.messaging.IEvent;

/**
 * Defines a generic interface for rules to be executed on specific objects
 * @author Eric A Amundson
 * @modelguid {56ED2D9B-29EE-44AE-94CC-02B0AC8A9424}
 */
public interface IRule {
    /**
     * Execute a specific rule related to the defined business object.
     * @param businessObject
     * @param event The event to populate.
     * @modelguid {4BEB8B9A-A9DC-4375-9C6D-E726D7A271BB}
     */
    public void execute(IEntityObject businessObject, IEvent event) throws RuleException;
}
