/* Generated by Together */

package mojo.km.rulemanagement;
import java.util.Collection;
import java.util.Iterator;
import mojo.km.messaging.IEvent;
import mojo.km.messaging.exception.ReturnException;

/**
 * Exception thrown if there is any problem processing a rule.
 * @modelguid {5DECFD49-8C57-477A-ACC8-1C90F3031D57}
*/
public class RuleException extends ReturnException {
	/** @modelguid {B30196C6-3F7B-4F67-AEE0-040B9626AF2D} */
    public RuleException()
    {
        super();
    }

	/** @modelguid {8146BEFA-6608-43BC-B490-E82D70ECBCE4} */
    public RuleException( String msg )
    {
        super(msg);
    }

	/** @modelguid {267571E3-8469-4318-9832-1CE6A9E88E32} */
    public RuleException(IEntityObject entityObject)
    {
        super();
       	if(entityObject instanceof IEvent){
			if(!hasEvent()){
				event = (IEvent)entityObject;
	        }
     	  }
    }

	/** @modelguid {5B5CED3F-4F4A-45B1-88DB-E164C14D5747} */
    public void insertRuleException(RuleException re)
    {
        exceptions.add(re);
    }

	/** @modelguid {B6EC73B6-0A44-497C-98DA-E7A41526343D} */
    public Iterator getRuleExceptions()
    {
        return exceptions.iterator();
    }

	/** @modelguid {0B5CF440-A6B9-412D-9D40-CDB8D6121816} */
    public int getCount()
    {
        return exceptions.size();
    }

	/** @modelguid {EC057DBB-6FAA-4615-984C-23EFAEF9E21B} */
    public boolean hasRuleExceptions()
    {
        return !exceptions.isEmpty();
    }

	/** @modelguid {E1397585-2F4F-482D-9450-536F01376429} */
    public boolean hasEvent()
    {
        return (event!=null);
    }

	/** @modelguid {5753C26A-230B-48DE-9034-E592B080957B} */
    public IEvent getEvent()
    {
    	return event;
    }

	/** @modelguid {A129C6E8-DA5B-4E81-A3D3-F63BA560370E} */
    public void setEvent(IEvent event)
    {
        this.event = event;
    }
    /**
     *@associates <{RuleException}>
     * @supplierCardinality 0..*
     * @supplierRole exceptions
     * @directed
     * @clientCardinality 1
     * @modelguid {825343AB-964A-41DA-8012-25E9494771B9}
     */
    private Collection exceptions = new java.util.Vector();
	/** @modelguid {B749ACD5-336D-40B9-91CF-A88871E1478C} */
    private IEvent event;

}
