/* Generated by Together */

package mojo.km.logging;

/**
 * Responsible for enabling tracking of execution.  Has method that could be used inside pre - post tags to enable to currently execution method. 
 * @modelguid {79F2A515-12EC-4D89-B7C8-F60B3817AA3C}
 */
public class ExecutionTracking {
	/** @modelguid {2E06F3C8-8016-428A-952F-AE02545234D5} */
    static public String PRE = "Precondition";
	/** @modelguid {6EC3308D-B2E5-4D90-8062-DD8DE63A2E0F} */
    static public String POST = "Postcondition";
	/** @modelguid {09B0A984-343F-4F10-AF36-38F87F9A05C2} */
    static public String INVARIANT = "Invariant";

    /**
     * Place inside of contract tags to display execution location.
     * @modelguid {BD464985-D0C5-4558-A0E3-4A30186849B3}
     */
    public static boolean track(String contractType)
    {
        System.out.println(contractType);
        return true;
    }
}
