/* Generated by Together */

package pd.appshell.logintransactions;

/**
 * @stereotype control
 * @eventPackage messaging.logintransactionsevents
 * @modelguid {A5AA09E9-5365-41D8-B272-70F312EFFEC0}
 */
public class LoginController {
    /**
     * @stereotype design
     * @serviceName asGetFavorites
     * @commandList pd.appshell.logintransactions.GetFavoritesCommand
     */
    public void getFavorites() { }

    /**
     * @stereotype design
     * @serviceName asGetTree
     */
//    public void getNavigationTree() { }
    // public void saveFavorites() {}

    /**
     * @stereotype design
     * @serviceName asGetPreferences
     * @modelguid {5B5927ED-04BC-49A5-AEB3-89A49E98B7B6}
     */
    public void getPreferences() { }

    /**
     * @stereotype design
     * @serviceName asSavePreferences
     * @modelguid {DFAAD278-D9DA-48CA-ACC2-E094FB0B7912}
     */
    public void savePreferences() { }                                                                                   


    /**
     * @stereotype design
     * @serviceName asAddfavorites
     * @modelguid {EA5E853B-21A9-465F-B9E1-3B0C6D0364DE}
     */
    public void addFavorites( String preferencesOID, String favoritesName ) { }



    /** @stereotype design
    * @serviceName asGetFeatureList 
    * @modelguid {1B7C5883-40CC-47CC-89D2-C6E8B841610E}
    * @commandList pd.appshell.logintransactions.GetFeatureListCommand
    */
    public void getFeatureList() { }
    //public void getPreferences() { }
    //public void savePreferences() { }

     /**
     * @stereotype design
     * @serviceName asRenameFavorites
     * @modelguid {5019B151-6532-43B7-91B4-E11675E238E1}
     */
    public void renameFavorites( String favoritesOID, String name) { }

     /**
     * @stereotype design
     * @serviceName asDeleteFavorites
     * @modelguid {A3383717-4CD9-48F5-A61B-3FD4E69A2AE7}
     */
    public void deleteFavorites( String favoritesOID) { }

    /**
     * @stereotype design
     * @serviceName asDeleteFeature
     * @modelguid {7AE7FE91-F52A-4F33-8E07-0B79BC78FE70}
     */
    public void deleteFeature( String featureOID, String favoritesOID) { }

    /**
     * @stereotype design
     * @serviceName asAddFeature
     * @modelguid {70946663-C670-4459-86BE-9E720256B609}
     */
    public void addFeature( String name, String favoritesOID) { }

    ///////////////////////// DPA: ADDED FOR APPSHELL WITH COMMON-CONTROLS TREE
	/**
	 * @stereotype design
	 * @serviceName asCCGetFavorites
     * @commandList pd.appshell.logintransactions.CCGetFavoritesCommand
	 */
	public void cCGetFavorites() { }
    
   /** @stereotype design
	* @serviceName asCCGetFeatureList 
	* @modelguid {1B7C5883-40CC-47CC-89D2-C6E8B841610E}
    * @commandList pd.appshell.logintransactions.GetFeatureListCommand
	*/
	public void cCGetFeatureList() { }
	////////////////////////////// DPA: END

}

