/* Generated by Together */

package mojo.km.logging.log4j;
import org.apache.log4j.*;

/**
* Responsible for redefinition of logging levels for mojo.
* @modelguid {48C862C6-2060-4BE3-83F7-44D293BBC3E9}
*/
public class MojoLevel extends org.apache.log4j.Level {    
    /**
     * @param level - level
     * @param levelStr - levelStr
     * @param sysLogEquivalent - sysLogEquivalent 
     * @modelguid {944197CA-B886-4595-9DA0-34F132E60CD7}
     */
    public MojoLevel(int level, String levelStr, int sysLogEquivalent)
    {
        super(level, levelStr, sysLogEquivalent );
    }


	/** @modelguid {9FDEB9D0-7497-4F9D-B848-8650FC24DA28} */
    static Level APPEXCEPTION = Level.ERROR;
	/** @modelguid {44FF8615-38D6-4308-98A0-006AD4FEFA06} */
    static Level ERROR = Level.ERROR;
	/** @modelguid {E47CFDF6-5DE9-4DA7-ACBF-D32CC3D41453} */
    static Level ERRORSTREAM = Level.ERROR;
	/** @modelguid {E8EE19AC-162C-49EB-AE41-2C2B0C46DAD7} */
    static Level OUTSTREAM = Level.INFO;
	/** @modelguid {6C2FBA60-CB0C-4637-B154-174DEDD77652} */
    static Level RUNTIMEEXCEPTION = Level.DEBUG;
	/** @modelguid {36C4543A-4CE0-4760-8288-54D365FB46DD} */
    static Level STACKTRACE = Level.DEBUG;
	/** @modelguid {31D057E5-304F-4FDD-B408-872436055C16} */
    static Level EXCEPTION = Level.WARN;
}
