/* Generated by Together */

package mojo.km.dispatch;
/**
* Type a reply dispatch as being used in a generic context.
* @modelguid {02D54BE0-2835-4798-94CB-9A6BD2A44882}
*/
public interface IGenericReply {
}
