/* Generated by Together */

package mojo.km.dispatch;

/**
 * Thrown when an event has no server set before being posted by the event manager. 
 * @modelguid {81E0E660-C63D-457B-894E-7DE3C14A8FC6}
 */
public class NoServerSetException extends RuntimeException {
	/** @modelguid {4396C47A-D1C1-40ED-B64E-FB5417FEAAF6} */
    public NoServerSetException() {
        super("Event has no server set.");
    }
}
