/* Generated by Together */

package mojo.km.dispatch;

/**
 * Thrown when a event has no service set before being posted in the event manager 
 * @modelguid {25B24E03-4A82-4575-84A2-D0943E04932F}
 */
public class NoTopicSetException extends RuntimeException {
	/** @modelguid {7AE6FC54-CE96-4BCC-A2E8-0238F410EB39} */
    public NoTopicSetException() {
        super("Event has no topic set");
    }
}
