/* Generated by Together */

package mojo.km.dispatch;
import mojo.km.messaging.IEvent;
import mojo.km.messaging.noop.NoReply;

/** @modelguid {5A20AD48-933C-4ED7-BA81-6EB4B67458C0} */
public class ReplyUtility {
	/** @modelguid {93A976C0-7DAF-4F3B-8DAA-40C84528CF29} */
    public IEvent postEvent( IEvent event ) {
/*
        if (!(reply instanceof NoReply)) {
            if (!(reply instanceof mojo.km.messaging.Composite.CompositeResponse)) {
                IEvent temp = reply;
                reply = new mojo.km.messaging.Composite.CompositeResponse();
				((mojo.km.messaging.Composite.CompositeResponse) reply).addResponse(temp);
            }
            ((mojo.km.messaging.Composite.CompositeResponse) reply).addResponse(event);
        } else {
            reply = event;
        }
*/
        ((mojo.km.messaging.Composite.CompositeResponse) reply).addResponse(event);
        return reply;
    }

	/** @modelguid {427AABAA-D756-49FE-88EF-B64D9CAEE9B2} */
    public IEvent current() {
        return reply;
    }

	/** @modelguid {5753E88C-72BB-4CE2-91E7-01E6092629AA} */
    private IEvent reply = new mojo.km.messaging.Composite.CompositeResponse();
}
