/* Generated by Together */

package mojo.km.utilities;

import mojo.km.config.AppProperties;
import mojo.km.config.MojoProperties;

/** @modelguid {468519D1-7D72-4CB2-BFE3-9FFECB1CA7DA} */
public class AppPropertyChanger {
	/** @modelguid {325988E8-149C-4064-B985-DFBE44F7CB4F} */
    public static void main(String[] argv) {
        if (argv.length != 2) {
            System.err.println("Usage:: java mojo.km.utilities.AppPropertyChanger <property name> <value>");
        }
        AppProperties.getInstance().setProperty(argv[0], argv[1] );
        MojoProperties.getInstance().saveProperties();
    }
}
