/* Generated by Together */

package mojo.km.utilities;

/** @modelguid {8923D956-E705-4B2C-986E-2906AFEB4B5E} */
public interface IOIDEvent {

    /**
    * sets the OID
    * @param anOID An OID.
    * @modelguid {7378C35D-0F6F-4237-9A88-796E63D7A964}
    */

    public void setOID(String OID);

    /**
    * returns the OID.
    * @return The OID.
    * @modelguid {84F1A1C7-87BA-4B92-AB82-4975DB36C0CC}
    */
    public String getOID();
}
