/* Generated by Together */

package mojo.km.utilities;

import java.io.Serializable;

/** @modelguid {A3F8BA12-1CA9-429C-9B30-2F23C15811F2} */
public interface IQueue extends Serializable {
    /*
     * Determines whether there are any items in the queue
     * @return boolean - true if there are item(s) in the queue; false otherwise
     * @modelguid {9456928D-58EB-41CC-93C9-7B2ED4713858}
     */
    public boolean isEmpty();

    /*
     * Adds an item to the bottom of the queue
     * @param anObject - item to add to the queue
     * @modelguid {F2D3B8D5-EB83-4DED-A115-C65D635AF8C4}
     */
    public void enqueue(Object x);

    /*
     * Removes and returns the first item in the queue
     * @return Object - first item in the queue
     * @exception Exception - thrown if the priority queue is empty
     * @modelguid {046A03A6-C6DA-44F9-B685-03254F104F09}
     */
    public Object dequeue() throws Exception;

    /*
     * Returns the first item in the queue
     * @return Object - first item in the queue
     * @exception Exception - thrown if the priority queue is empty
     * @modelguid {7BD6306D-C032-42C4-8A54-862E61C2AEA0}
     */
    public Object peekFront() throws Exception;

    /*
     * Returns the last item in the queue
     * @return Object - last item in the queue
     * @exception Exception - thrown if the priority queue is empty
     * @modelguid {DCFE71D2-4E7C-4C85-A765-CAC835D2B81D}
     */
    public Object peekBack() throws Exception;
}
