/* Generated by Together */

package mojo.km.utilities;
import mojo.km.messaging.RequestEvent;
  /**
   * This a concrete class that implements the IOIDEvent Interface
   *
   * @modelguid {E688BD06-557D-4197-BE13-E2BE21DEAA7F}
   * */
public class OIDEvent extends RequestEvent implements IOIDEvent {
    /**
    * sets the OID
    * @param anOID An OID.
    * @modelguid {FD144931-AE5E-4F23-8D43-F995D9AB0AC3}
    */

    public void setOID(String OID){
        this.OID = OID;
    }
    /**
    * gets the OID
    * @return the OID
    * @modelguid {0F12C433-0D82-4E62-986E-91164A14BDF5}
    */
    public String getOID(){
        return this.OID;
    }

	/** @modelguid {DE84C62A-94A0-4649-B466-F58F259826D5} */
    private String OID;
}
