/* Generated by Together */

package mojo.km.utilities;
import java.io.ByteArrayOutputStream;
import java.io.ObjectOutputStream;
import mojo.km.context.ContextManager;

/**
* Functions for managing serialization of java objects.
* @modelguid {2B3980CC-129C-4B06-8AC0-3047859848AB}
*/
public class SerializationUtility {
    /**
     * Returns if object is serializable.
     * @modelguid {5881DF21-8CB8-4A2A-A81F-98E78DD64459}
     */
    static public boolean isSerializable( Object anObject )
    {
        if (ContextManager.getServerName().equals("MojoAddinController")) {
            return true;
        }
        try {
       	 	ByteArrayOutputStream outStream = new ByteArrayOutputStream();
            ObjectOutputStream oStream = new ObjectOutputStream(outStream);
            oStream.writeObject(anObject);
            outStream.close();
        } catch (Throwable t) {
            System.err.println("Object is not serializable :: " + anObject );
            t.printStackTrace();
            return false;
        }
        return true;
    }
}
