/* Generated by Together */

package mojo.km.properties;

/**
 * Default no action contract implementation for property copying.
 * @author Eric A Amundson
 * @version 1.0
 * @modelguid {120037D5-F9A0-4AF2-8D79-D656FCDCD815}
 **/
public class DefaultContract implements IContract {
    /**
     * implements rules for checking property values after setter method is invoked.
     * @exception <{FailedPostconditionException}>
     * @modelguid {6C9DE507-8455-4635-9DCE-B17E6A70B0D3}
     */
    public void checkPostcondition(Object value) throws FailedPostconditionException {}
    
    /**
     * implements rules for checking property values before setter method is invoked.
     * @exception <{FailedPreconditionException}>
     * @modelguid {5B2C5210-632E-4E52-ACDC-6A1D0CE20423}
     */
    public void checkPrecondition(Object value) throws FailedPreconditionException {}

    /**
     * indicates whether the property is readable before getter method is invoked.
     * @return boolean true (default)
     * @modelguid {9215896D-2942-4060-92BC-5B915BE039A6}
     */
    public boolean isReadable() {
        return true;
    }

    /**
     * indicates whether the property is writable before setter method is invoked.
     * @return boolean true (default)
     * @modelguid {424322BE-9428-43AD-A5A9-46D635D8568F}
     */
    public boolean isWritable() {
        return true;
    }
}
