/* Generated by Together */

package mojo.km.properties;

/**
* Responsible for implementing a no action contract implementation for property copying.
* @author Eric A Amundson
* @version 1.0
* @modelguid {5EB1FDCA-508B-45E9-B1B5-272C8B76A718}
**/
public class DefaultPropertyBundle implements IPropertyBundle {
	/** @modelguid {D002F4BB-BF15-4233-A8DC-F5AC013F5014} */
    public IContract getContract(String propertyName) { return defaultContract; }

	/** @modelguid {48B623CA-1467-4227-82A4-DCDFE5EE3CF5} */
    IContract defaultContract = new DefaultContract();
}
