/* Generated by Together */

package mojo.km.properties;

/**
 * Thrown if the setting of property failes any precondition checks for value setting. 
 * @modelguid {C5AF90A2-D55B-4B9C-94C6-F6C1D59653AF}
 */
public class FailedPostconditionException extends Exception {
	/** @modelguid {5F5A1B1B-6C6C-416B-A2E2-5F8AE2126C3A} */
    public FailedPostconditionException() {
    }

	/** @modelguid {33B0A977-6624-49A8-B84D-70500ADD4CAB} */
    public FailedPostconditionException(String msg) {
        super(msg);
    }
}
