/* Generated by Together */

package mojo.km.properties;

/**
 * Thrown if the setting of property failes any precondition checks for value setting. 
 * @modelguid {373A4E33-D951-47AA-871E-B16AE82EBEC4}
 */
public class FailedPreconditionException extends Exception {
	/** @modelguid {129CE912-EE5D-4E0A-8B60-CF6E7F07BC4C} */
    public FailedPreconditionException() {}

	/** @modelguid {E2F7CB8D-B284-4103-9A24-243D3D8513F0} */
    public FailedPreconditionException(String msg) {
        super(msg);
    }
}
