/* Generated by Together */

package mojo.km.properties;

/**
 * Defines the interface that will enforce various validation rules for the contract of getting and setting various application properties. 
 * @author Eric A Amundson
 * @stereotype interface
 * @modelguid {B1574095-87A0-469B-8E31-DFDF5004F4C4}
 */
public interface IContract {
    /**
     * implements rules for checking property values before setter method is invoked.
     * @exception FailedPreconditionException 
     * @modelguid {04B60CE5-88AB-4B0C-8EF7-2315F69DF570}
     */
    public void checkPrecondition(Object value) throws FailedPreconditionException;

    /**
     * implements rules for checking property values after setter method is invoked.
     * @exception FailedPostconditionException
     * @modelguid {90467E6E-C5B4-46C5-9A29-1F3729E1B0A3}
     */
    public void checkPostcondition(Object value) throws FailedPostconditionException;

    /**
     * indicates whether the property is readable before getter method is invoked.
     * @return boolean
     * @modelguid {7DBE9596-8F8E-436A-A32E-56F14BA375C9}
     */
    public boolean isReadable();

    /**
     * indicates whether the property is writable before setter method is invoked.
     * @return boolean
     * @modelguid {24DBB518-A260-4CE3-BE97-88B1A2175F91}
     */
    public boolean isWritable();
}
