/* Generated by Together */

package mojo.km.properties;

/**
 * Defines an interface for access bundles of IContract checkers on specific properties managed within a service context. 
 * @modelguid {CD6879BC-A128-4EA1-BF48-B48C33AA777F}
 */
public interface IPropertyBundle {
	/** @modelguid {78A70579-7766-471F-82EC-F1CACD00E735} */
    public IContract getContract( String propertyName );
}
