/* Generated by Together */

package mojo.naming;

public class CalendarConstants {

	public static final String ONCE = "Once";
	public static final String ONCE_SCHEDULE_CLASS = "mojo.km.scheduling.OnceSchedule";

	public static final String HALF_HOURLY = "Half Hourly";
  	public static final String HALF_HOURLY_SCHEDULE_CLASS = "mojo.km.scheduling.HalfHourlySchedule";

  	public static final String HOURLY = "Hourly";
	public static final String HOURLY_SCHEDULE_CLASS = "mojo.km.scheduling.HourlySchedule";

    public static final String DAILY = "Daily";
	public static final String DAILY_SCHEDULE_CLASS = "mojo.km.scheduling.DailySchedule";

    public static final String WEEKLY = "Weekly";
    public static final String WEEKLY_SCHEDULE_CLASS = "mojo.km.scheduling.WeeklySchedule";

    public static final String BI_WEEKLY = "Bi Weekly";
    public static final String BI_WEEKLY_SCHEDULE_CLASS = "mojo.km.scheduling.BiWeeklySchedule";

	public static final String MONTHLY = "Monthly";
	public static final String MONTHLY_SCHEDULE_CLASS = "mojo.km.scheduling.MonthlySchedule";
	
	public static final String QUARTERLY = "Quarterly";
	public static final String QUARTERLY_SCHEDULE_CLASS = "mojo.km.scheduling.QuarterlySchedule";


	public static final String YEARLY = "Yearly";
	public static final String YEARLY_SCHEDULE_CLASS = "mojo.km.scheduling.YearlySchedule";

	public static final String ALWAYS = "Always";
	public static final String ALWAYS_SCHEDULE_CLASS = "mojo.km.scheduling.RunAlways";

	public static final String DELIMITER = "|";
	public static final String SEPERATOR = ",";
	public static final String LIST_SEPERATOR = ";";

	public static String getSchedulerClassName(String frequency) throws Exception {

        if (frequency.equals(ONCE)){
            return ONCE_SCHEDULE_CLASS;
        }

        if (frequency.equals(HALF_HOURLY)){
            return HALF_HOURLY_SCHEDULE_CLASS;
        }

        if (frequency.equals(HOURLY)){
            return HOURLY_SCHEDULE_CLASS;
        }

        if (frequency.equals(DAILY)){
            return DAILY_SCHEDULE_CLASS;
        }
        if (frequency.equals(WEEKLY)){
            return WEEKLY_SCHEDULE_CLASS;
        }

        if (frequency.equals(BI_WEEKLY)){
            return BI_WEEKLY_SCHEDULE_CLASS;
        }

        if (frequency.equals(MONTHLY)){
            return MONTHLY_SCHEDULE_CLASS;
        }

	 if (frequency.equals(QUARTERLY)){
            return QUARTERLY_SCHEDULE_CLASS;
        }

        if (frequency.equals(YEARLY)){
            return YEARLY_SCHEDULE_CLASS;
        }
        if (frequency.equals(ALWAYS)){
            return ALWAYS_SCHEDULE_CLASS;
        }
        throw new Exception("The Frequency provided has not been defined in the system.");
    }

}
